//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.14 at 11:52:07 AM IST 
//


package com.npst.upiserver.npcischema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Head" type="{http://npci.org/upi/schema/}headType"/>
 *         &lt;element name="Txn" type="{http://npci.org/upi/schema/}payTrans"/>
 *         &lt;element name="VaeList" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Vae" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="key" type="{http://npci.org/upi/schema/}keyType"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="op" type="{http://npci.org/upi/schema/}opType" />
 *                           &lt;attribute name="seqNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="addr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="logo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "txn",
    "vaeList"
})
@XmlRootElement(name = "ReqManageVae")
public class ReqManageVae {

    @XmlElement(name = "Head", required = true)
    protected HeadType head;
    @XmlElement(name = "Txn", required = true)
    protected PayTrans txn;
    @XmlElement(name = "VaeList", required = true)
    protected List<ReqManageVae.VaeList> vaeList;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link HeadType }
     *     
     */
    public HeadType getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeadType }
     *     
     */
    public void setHead(HeadType value) {
        this.head = value;
    }

    /**
     * Gets the value of the txn property.
     * 
     * @return
     *     possible object is
     *     {@link PayTrans }
     *     
     */
    public PayTrans getTxn() {
        return txn;
    }

    /**
     * Sets the value of the txn property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayTrans }
     *     
     */
    public void setTxn(PayTrans value) {
        this.txn = value;
    }

    /**
     * Gets the value of the vaeList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vaeList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVaeList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReqManageVae.VaeList }
     * 
     * 
     */
    public List<ReqManageVae.VaeList> getVaeList() {
        if (vaeList == null) {
            vaeList = new ArrayList<ReqManageVae.VaeList>();
        }
        return this.vaeList;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Vae" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="key" type="{http://npci.org/upi/schema/}keyType"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="op" type="{http://npci.org/upi/schema/}opType" />
     *                 &lt;attribute name="seqNum" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="addr" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="logo" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vae"
    })
    public static class VaeList {

        @XmlElement(name = "Vae", required = true)
        protected List<ReqManageVae.VaeList.Vae> vae;

        /**
         * Gets the value of the vae property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vae property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVae().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ReqManageVae.VaeList.Vae }
         * 
         * 
         */
        public List<ReqManageVae.VaeList.Vae> getVae() {
            if (vae == null) {
                vae = new ArrayList<ReqManageVae.VaeList.Vae>();
            }
            return this.vae;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="key" type="{http://npci.org/upi/schema/}keyType"/>
         *       &lt;/sequence>
         *       &lt;attribute name="op" type="{http://npci.org/upi/schema/}opType" />
         *       &lt;attribute name="seqNum" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="addr" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="logo" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "key"
        })
        public static class Vae {

            @XmlElement(required = true)
            protected KeyType key;
            @XmlAttribute(name = "op")
            protected OpType op;
            @XmlAttribute(name = "seqNum")
            protected String seqNum;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "addr")
            protected String addr;
            @XmlAttribute(name = "logo")
            protected String logo;
            @XmlAttribute(name = "url")
            protected String url;

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link KeyType }
             *     
             */
            public KeyType getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link KeyType }
             *     
             */
            public void setKey(KeyType value) {
                this.key = value;
            }

            /**
             * Gets the value of the op property.
             * 
             * @return
             *     possible object is
             *     {@link OpType }
             *     
             */
            public OpType getOp() {
                return op;
            }

            /**
             * Sets the value of the op property.
             * 
             * @param value
             *     allowed object is
             *     {@link OpType }
             *     
             */
            public void setOp(OpType value) {
                this.op = value;
            }

            /**
             * Gets the value of the seqNum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSeqNum() {
                return seqNum;
            }

            /**
             * Sets the value of the seqNum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSeqNum(String value) {
                this.seqNum = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the addr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddr() {
                return addr;
            }

            /**
             * Sets the value of the addr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddr(String value) {
                this.addr = value;
            }

            /**
             * Gets the value of the logo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLogo() {
                return logo;
            }

            /**
             * Sets the value of the logo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLogo(String value) {
                this.logo = value;
            }

            /**
             * Gets the value of the url property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrl() {
                return url;
            }

            /**
             * Sets the value of the url property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrl(String value) {
                this.url = value;
            }

        }

    }

}
