//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.14 at 11:57:36 AM IST 
//


package com.npst.upiserver.npcischema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pspVersionDesc.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="pspVersionDesc">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="UPI 1.0 BASE VERSION"/>
 *     &lt;enumeration value="UPI 2.0: ALL TAG LEVEL CHANGES"/>
 *     &lt;enumeration value="UPI 2.0 version: All tag level changes"/>
 *     &lt;enumeration value="MANDATE"/>
 *     &lt;enumeration value="REFUND"/>
 *     &lt;enumeration value="AADHAAR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "pspVersionDesc")
@XmlEnum
public enum PspVersionDesc {

    @XmlEnumValue("UPI 1.0 BASE VERSION")
    UPI_1_0_BASE_VERSION("UPI 1.0 BASE VERSION"),
    @XmlEnumValue("UPI 2.0: ALL TAG LEVEL CHANGES")
    UPI_2_0_ALL_TAG_LEVEL_CHANGES("UPI 2.0: ALL TAG LEVEL CHANGES"),
    @XmlEnumValue("UPI 2.0 version: All tag level changes")
    UPI_2_0_VERSION_ALL_TAG_LEVEL_CHANGES("UPI 2.0 version: All tag level changes"),
    MANDATE("MANDATE"),
    REFUND("REFUND"),
    AADHAAR("AADHAAR");
    private final String value;

    PspVersionDesc(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PspVersionDesc fromValue(String v) {
        for (PspVersionDesc c: PspVersionDesc.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
