package com.npst.upi.hor;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Beneficiary generated by hbm2java
 */
@Entity
@Table(name = "beneficiary")
public class Beneficiary implements java.io.Serializable {
	
	private Integer	beneid;
	private Date	addeddt;
	private String	payeeaccno;
	private String	payeeaddr;
	private String	payeeadharno;
	private String	payeecode;
	private String	payeeifsc;
	private String	payeeiin;
	private String	payeemmid;
	private String	payeemobilen;
	private String	payeename;
	private String	payeeseqno;
	private String	payeetype;
	private Integer	regid;
	private Integer	status;
	private Date	updated;
	private Integer	type;
	
	public Beneficiary() {
	}
	
	public Beneficiary(Date addeddt, String payeeaccno, String payeeaddr, String payeeadharno, String payeecode,
			String payeeifsc, String payeeiin, String payeemmid, String payeemobilen, String payeename,
			String payeeseqno, String payeetype, Integer regid, Integer status, Date updated) {
		this.addeddt = addeddt;
		this.payeeaccno = payeeaccno;
		this.payeeaddr = payeeaddr;
		this.payeeadharno = payeeadharno;
		this.payeecode = payeecode;
		this.payeeifsc = payeeifsc;
		this.payeeiin = payeeiin;
		this.payeemmid = payeemmid;
		this.payeemobilen = payeemobilen;
		this.payeename = payeename;
		this.payeeseqno = payeeseqno;
		this.payeetype = payeetype;
		this.regid = regid;
		this.status = status;
		this.updated = updated;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ADDEDDT", length = 19)
	public Date getAddeddt() {
		return this.addeddt;
	}
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	
	@Column(name = "BENEID", unique = true, nullable = false)
	public Integer getBeneid() {
		return this.beneid;
	}
	
	@Column(name = "PAYEEACCNO", length = 50)
	public String getPayeeaccno() {
		return this.payeeaccno;
	}
	
	@Column(name = "PAYEEADDR", length = 51)
	public String getPayeeaddr() {
		return this.payeeaddr;
	}
	
	@Column(name = "PAYEEADHARNO", length = 50)
	public String getPayeeadharno() {
		return this.payeeadharno;
	}
	
	@Column(name = "PAYEECODE", length = 20)
	public String getPayeecode() {
		return this.payeecode;
	}
	
	@Column(name = "PAYEEIFSC", length = 50)
	public String getPayeeifsc() {
		return this.payeeifsc;
	}
	
	@Column(name = "PAYEEIIN", length = 50)
	public String getPayeeiin() {
		return this.payeeiin;
	}
	
	@Column(name = "PAYEEMMID", length = 50)
	public String getPayeemmid() {
		return this.payeemmid;
	}
	
	@Column(name = "PAYEEMOBILEN", length = 50)
	public String getPayeemobilen() {
		return this.payeemobilen;
	}
	
	@Column(name = "PAYEENAME", length = 30)
	public String getPayeename() {
		return this.payeename;
	}
	
	@Column(name = "PAYEESEQNO", length = 20)
	public String getPayeeseqno() {
		return this.payeeseqno;
	}
	
	@Column(name = "PAYEETYPE", length = 20)
	public String getPayeetype() {
		return this.payeetype;
	}
	
	@Column(name = "REGID")
	public Integer getRegid() {
		return this.regid;
	}
	
	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}
	
	@Column(name = "TYPE")
	public Integer getType() {
		return type;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED", length = 19)
	public Date getUpdated() {
		return this.updated;
	}
	
	public void setAddeddt(Date addeddt) {
		this.addeddt = addeddt;
	}
	
	public void setBeneid(Integer beneid) {
		this.beneid = beneid;
	}
	
	public void setPayeeaccno(String payeeaccno) {
		this.payeeaccno = payeeaccno;
	}
	
	public void setPayeeaddr(String payeeaddr) {
		this.payeeaddr = payeeaddr;
	}
	
	public void setPayeeadharno(String payeeadharno) {
		this.payeeadharno = payeeadharno;
	}
	
	public void setPayeecode(String payeecode) {
		this.payeecode = payeecode;
	}
	
	public void setPayeeifsc(String payeeifsc) {
		this.payeeifsc = payeeifsc;
	}
	
	public void setPayeeiin(String payeeiin) {
		this.payeeiin = payeeiin;
	}
	
	public void setPayeemmid(String payeemmid) {
		this.payeemmid = payeemmid;
	}
	
	public void setPayeemobilen(String payeemobilen) {
		this.payeemobilen = payeemobilen;
	}
	
	public void setPayeename(String payeename) {
		this.payeename = payeename;
	}
	
	public void setPayeeseqno(String payeeseqno) {
		this.payeeseqno = payeeseqno;
	}
	
	public void setPayeetype(String payeetype) {
		this.payeetype = payeetype;
	}
	
	public void setRegid(Integer regid) {
		this.regid = regid;
	}
	
	public void setStatus(Integer status) {
		this.status = status;
	}
	
	public void setType(Integer type) {
		this.type = type;
	}
	
	public void setUpdated(Date updated) {
		this.updated = updated;
	}
	
}
