package com.npst.upi.hor;
// Generated 2 Nov, 2017 2:12:59 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Blockedvpa generated by hbm2java
 */
@Entity
@Table(name = "blockedvpa")
public class Blockedvpa implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -8455117689573791270L;
	private Integer blockedvpaid;
	private String blockvpa;
	private String mobileno;
	private Date addeddt;

	public Blockedvpa() {
	}

	public Blockedvpa(String blockvpa, String mobileno, Date addeddt) {
		this.blockvpa = blockvpa;
		this.mobileno = mobileno;
		this.addeddt = addeddt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ADDEDDT", length = 19)
	public Date getAddeddt() {
		return this.addeddt;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "BLOCKEDVPAID", unique = true, nullable = false)
	public Integer getBlockedvpaid() {
		return this.blockedvpaid;
	}

	@Column(name = "BLOCKVPA", length = 50)
	public String getBlockvpa() {
		return this.blockvpa;
	}

	@Column(name = "MOBILENO", length = 12)
	public String getMobileno() {
		return this.mobileno;
	}

	public void setAddeddt(Date addeddt) {
		this.addeddt = addeddt;
	}

	public void setBlockedvpaid(Integer blockedvpaid) {
		this.blockedvpaid = blockedvpaid;
	}

	public void setBlockvpa(String blockvpa) {
		this.blockvpa = blockvpa;
	}

	public void setMobileno(String mobileno) {
		this.mobileno = mobileno;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Blockedvpa [");
		if (blockedvpaid != null) {
			builder.append("blockedvpaid=");
			builder.append(blockedvpaid);
			builder.append(", ");
		}
		if (blockvpa != null) {
			builder.append("blockvpa=");
			builder.append(blockvpa);
			builder.append(", ");
		}
		if (mobileno != null) {
			builder.append("mobileno=");
			builder.append(mobileno);
			builder.append(", ");
		}
		if (addeddt != null) {
			builder.append("addeddt=");
			builder.append(addeddt);
		}
		builder.append("]");
		return builder.toString();
	}

}
