package com.npst.upi.hor;
// Generated 13 Nov, 2017 3:32:41 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Useractivity generated by hbm2java
 */
@Entity
@Table(name = "useractivity")
public class Useractivity implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1658414291381306198L;
	private Integer useractivityid;
	private Integer regid;
	private Integer type;
	private Date activitydt;
	private Integer description;
	private String password;

	public Useractivity() {
	}

	public Useractivity(Integer regid, Integer type, Date activitydt, Integer description, String password) {
		this.regid = regid;
		this.type = type;
		this.activitydt = activitydt;
		this.description = description;
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACTIVITYDT", length = 19)
	public Date getActivitydt() {
		return this.activitydt;
	}

	@Column(name = "DESCRIPTION")
	public Integer getDescription() {
		return this.description;
	}

	@Column(name = "PASSWORD", length = 100)
	public String getPassword() {
		return this.password;
	}

	@Column(name = "REGID")
	public Integer getRegid() {
		return this.regid;
	}

	@Column(name = "TYPE")
	public Integer getType() {
		return this.type;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "USERACTIVITYID", unique = true, nullable = false)
	public Integer getUseractivityid() {
		return this.useractivityid;
	}

	public void setActivitydt(Date activitydt) {
		this.activitydt = activitydt;
	}

	public void setDescription(Integer description) {
		this.description = description;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public void setRegid(Integer regid) {
		this.regid = regid;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public void setUseractivityid(Integer useractivityid) {
		this.useractivityid = useractivityid;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Useractivity [");
		if (useractivityid != null) {
			builder.append("useractivityid=");
			builder.append(useractivityid);
			builder.append(", ");
		}
		if (regid != null) {
			builder.append("regid=");
			builder.append(regid);
			builder.append(", ");
		}
		if (type != null) {
			builder.append("type=");
			builder.append(type);
			builder.append(", ");
		}
		if (activitydt != null) {
			builder.append("activitydt=");
			builder.append(activitydt);
			builder.append(", ");
		}
		if (description != null) {
			builder.append("description=");
			builder.append(description);
			builder.append(", ");
		}
		if (password != null) {
			builder.append("password=");
			builder.append(password);
		}
		builder.append("]");
		return builder.toString();
	}

}
