package com.npst.middleware.entity;
// Generated 5 Mar, 2017 5:02:39 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ListaccountId generated by hbm2java
 */
@Embeddable
public class ListaccountId implements java.io.Serializable {
	
	/**
	 *
	 */
	private static final long	serialVersionUID	= 1L;
	private String				mobNo;
	private int					sno;
	
	public ListaccountId() {
	}
	
	public ListaccountId(String mobNo, int sno) {
		this.mobNo = mobNo;
		this.sno = sno;
	}
	
	@Override
	public boolean equals(Object other) {
		if ((this == other)) { return true; }
		if ((other == null)) { return false; }
		if (!(other instanceof ListaccountId)) { return false; }
		ListaccountId castOther = (ListaccountId) other;
		
		return ((this.getMobNo() == castOther.getMobNo()) || (this.getMobNo() != null && castOther.getMobNo() != null
				&& this.getMobNo().equals(castOther.getMobNo()))) && (this.getSno() == castOther.getSno());
	}
	
	@Column(name = "MobNo", nullable = false, length = 12)
	public String getMobNo() {
		return this.mobNo;
	}
	
	@Column(name = "Sno", nullable = false)
	public int getSno() {
		return this.sno;
	}
	
	@Override
	public int hashCode() {
		int result = 17;
		
		result = 37 * result + (getMobNo() == null ? 0 : this.getMobNo().hashCode());
		result = 37 * result + this.getSno();
		return result;
	}
	
	public void setMobNo(String mobNo) {
		this.mobNo = mobNo;
	}
	
	public void setSno(int sno) {
		this.sno = sno;
	}
	
}
