package com.npst.middleware.entity;
// Generated 5 Mar, 2017 5:02:39 PM by Hibernate Tools 5.2.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Regvpa generated by hbm2java
 */
@Entity
@Table(name = "regvpa", uniqueConstraints = @UniqueConstraint(columnNames = "MobNo"))
public class Regvpa implements java.io.Serializable {
	
	/**
	 *
	 */
	private static final long	serialVersionUID	= 1L;
	private String				vpa;
	private String				mobNo;
	private String				fname;
	private String				mname;
	private String				lname;
	private Date				dob;
	private String				gender;
	private String				securityQues;
	private String				securityAns;
	private String				emailId;
	private String				loginPin;
	private String				aadhaarNo;
	private String				status;
	private Date				lastLogin;
	private Date				createdDate;
	private Date				updatedDate;
	private String				gcmToken;
	private String				appVer;
	private String				appOs;
	private Date				expDate;
	private Date				lastChangePass;
	private String				failCount;
	private Date				blockTime;
	private Date				serverTokenDt;
	private String				serverToken;
	
	public Regvpa() {
	}
	
	public Regvpa(String vpa) {
		this.vpa = vpa;
	}
	
	public Regvpa(String vpa, String mobNo, String fname, String mname, String lname, Date dob, String gender,
			String securityQues, String securityAns, String emailId, String loginPin, String aadhaarNo, String status,
			Date lastLogin, Date createdDate, Date updatedDate, String gcmToken, String appVer, String appOs,
			Date expDate, Date lastChangePass, String failCount, Date blockTime, Date serverTokenDt,
			String serverToken) {
		this.vpa = vpa;
		this.mobNo = mobNo;
		this.fname = fname;
		this.mname = mname;
		this.lname = lname;
		this.dob = dob;
		this.gender = gender;
		this.securityQues = securityQues;
		this.securityAns = securityAns;
		this.emailId = emailId;
		this.loginPin = loginPin;
		this.aadhaarNo = aadhaarNo;
		this.status = status;
		this.lastLogin = lastLogin;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.gcmToken = gcmToken;
		this.appVer = appVer;
		this.appOs = appOs;
		this.expDate = expDate;
		this.lastChangePass = lastChangePass;
		this.failCount = failCount;
		this.blockTime = blockTime;
		this.serverTokenDt = serverTokenDt;
		this.serverToken = serverToken;
	}
	
	@Column(name = "AadhaarNo", length = 12)
	public String getAadhaarNo() {
		return this.aadhaarNo;
	}
	
	@Column(name = "AppOS", length = 10)
	public String getAppOs() {
		return this.appOs;
	}
	
	@Column(name = "AppVer", length = 5)
	public String getAppVer() {
		return this.appVer;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BlockTime", length = 19)
	public Date getBlockTime() {
		return this.blockTime;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Dob", length = 19)
	public Date getDob() {
		return this.dob;
	}
	
	@Column(name = "EmailId", length = 50)
	public String getEmailId() {
		return this.emailId;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ExpDate", length = 19)
	public Date getExpDate() {
		return this.expDate;
	}
	
	@Column(name = "FailCount", length = 1)
	public String getFailCount() {
		return this.failCount;
	}
	
	@Column(name = "FName", length = 50)
	public String getFname() {
		return this.fname;
	}
	
	@Column(name = "GcmToken", length = 1000)
	public String getGcmToken() {
		return this.gcmToken;
	}
	
	@Column(name = "Gender", length = 11)
	public String getGender() {
		return this.gender;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastChangePass", length = 19)
	public Date getLastChangePass() {
		return this.lastChangePass;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastLogin", length = 19)
	public Date getLastLogin() {
		return this.lastLogin;
	}
	
	@Column(name = "LName", length = 50)
	public String getLname() {
		return this.lname;
	}
	
	@Column(name = "LoginPin", length = 30)
	public String getLoginPin() {
		return this.loginPin;
	}
	
	@Column(name = "MNAme", length = 50)
	public String getMname() {
		return this.mname;
	}
	
	@Column(name = "MobNo", unique = true, length = 12)
	public String getMobNo() {
		return this.mobNo;
	}
	
	@Column(name = "SecurityAns", length = 50)
	public String getSecurityAns() {
		return this.securityAns;
	}
	
	@Column(name = "SecurityQues", length = 80)
	public String getSecurityQues() {
		return this.securityQues;
	}
	
	@Column(name = "ServerToken", length = 35)
	public String getServerToken() {
		return this.serverToken;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ServerTokenDt", length = 19)
	public Date getServerTokenDt() {
		return this.serverTokenDt;
	}
	
	@Column(name = "Status", length = 10)
	public String getStatus() {
		return this.status;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDate", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}
	
	@Id
	
	@Column(name = "Vpa", unique = true, nullable = false, length = 50)
	public String getVpa() {
		return this.vpa;
	}
	
	public void setAadhaarNo(String aadhaarNo) {
		this.aadhaarNo = aadhaarNo;
	}
	
	public void setAppOs(String appOs) {
		this.appOs = appOs;
	}
	
	public void setAppVer(String appVer) {
		this.appVer = appVer;
	}
	
	public void setBlockTime(Date blockTime) {
		this.blockTime = blockTime;
	}
	
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	
	public void setDob(Date dob) {
		this.dob = dob;
	}
	
	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}
	
	public void setExpDate(Date expDate) {
		this.expDate = expDate;
	}
	
	public void setFailCount(String failCount) {
		this.failCount = failCount;
	}
	
	public void setFname(String fname) {
		this.fname = fname;
	}
	
	public void setGcmToken(String gcmToken) {
		this.gcmToken = gcmToken;
	}
	
	public void setGender(String gender) {
		this.gender = gender;
	}
	
	public void setLastChangePass(Date lastChangePass) {
		this.lastChangePass = lastChangePass;
	}
	
	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}
	
	public void setLname(String lname) {
		this.lname = lname;
	}
	
	public void setLoginPin(String loginPin) {
		this.loginPin = loginPin;
	}
	
	public void setMname(String mname) {
		this.mname = mname;
	}
	
	public void setMobNo(String mobNo) {
		this.mobNo = mobNo;
	}
	
	public void setSecurityAns(String securityAns) {
		this.securityAns = securityAns;
	}
	
	public void setSecurityQues(String securityQues) {
		this.securityQues = securityQues;
	}
	
	public void setServerToken(String serverToken) {
		this.serverToken = serverToken;
	}
	
	public void setServerTokenDt(Date serverTokenDt) {
		this.serverTokenDt = serverTokenDt;
	}
	
	public void setStatus(String status) {
		this.status = status;
	}
	
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
	public void setVpa(String vpa) {
		this.vpa = vpa;
	}
	
}
