//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.14 at 11:57:36 AM IST 
//


package com.npst.upiserver.npcischema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for institutionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="institutionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://npci.org/upi/schema/}institutionName"/>
 *         &lt;element name="Purpose" type="{http://npci.org/upi/schema/}institutionPurpose"/>
 *         &lt;element name="Originator" type="{http://npci.org/upi/schema/}institutionOriginator"/>
 *         &lt;element name="Beneficiary" type="{http://npci.org/upi/schema/}institutionBeneficiary"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{http://npci.org/upi/schema/}institutionAttrType" />
 *       &lt;attribute name="route" use="required" type="{http://npci.org/upi/schema/}institutionRoute" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "institutionType", propOrder = {
    "name",
    "purpose",
    "originator",
    "beneficiary"
})
public class InstitutionType {

    @XmlElement(name = "Name", required = true)
    protected InstitutionName name;
    @XmlElement(name = "Purpose", required = true)
    protected InstitutionPurpose purpose;
    @XmlElement(name = "Originator", required = true)
    protected InstitutionOriginator originator;
    @XmlElement(name = "Beneficiary", required = true)
    protected InstitutionBeneficiary beneficiary;
    @XmlAttribute(name = "type", required = true)
    protected InstitutionAttrType type;
    @XmlAttribute(name = "route", required = true)
    protected InstitutionRoute route;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionName }
     *     
     */
    public InstitutionName getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionName }
     *     
     */
    public void setName(InstitutionName value) {
        this.name = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionPurpose }
     *     
     */
    public InstitutionPurpose getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionPurpose }
     *     
     */
    public void setPurpose(InstitutionPurpose value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the originator property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionOriginator }
     *     
     */
    public InstitutionOriginator getOriginator() {
        return originator;
    }

    /**
     * Sets the value of the originator property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionOriginator }
     *     
     */
    public void setOriginator(InstitutionOriginator value) {
        this.originator = value;
    }

    /**
     * Gets the value of the beneficiary property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionBeneficiary }
     *     
     */
    public InstitutionBeneficiary getBeneficiary() {
        return beneficiary;
    }

    /**
     * Sets the value of the beneficiary property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionBeneficiary }
     *     
     */
    public void setBeneficiary(InstitutionBeneficiary value) {
        this.beneficiary = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionAttrType }
     *     
     */
    public InstitutionAttrType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionAttrType }
     *     
     */
    public void setType(InstitutionAttrType value) {
        this.type = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionRoute }
     *     
     */
    public InstitutionRoute getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionRoute }
     *     
     */
    public void setRoute(InstitutionRoute value) {
        this.route = value;
    }

}
