//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.14 at 11:57:36 AM IST 
//


package com.npst.upiserver.npcischema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for identifierType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="identifierType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="subCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="merchantType" type="{http://npci.org/upi/schema/}merchantIdentifierType" />
 *       &lt;attribute name="merchantGenre" type="{http://npci.org/upi/schema/}merchantGenreType" />
 *       &lt;attribute name="onBoardingType" type="{http://npci.org/upi/schema/}merchantOnBoardingType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "identifierType")
public class IdentifierType {

    @XmlAttribute(name = "subCode")
    protected String subCode;
    @XmlAttribute(name = "mid")
    protected String mid;
    @XmlAttribute(name = "sid")
    protected String sid;
    @XmlAttribute(name = "tid")
    protected String tid;
    @XmlAttribute(name = "merchantType")
    protected MerchantIdentifierType merchantType;
    @XmlAttribute(name = "merchantGenre")
    protected MerchantGenreType merchantGenre;
    @XmlAttribute(name = "onBoardingType")
    protected MerchantOnBoardingType onBoardingType;

    /**
     * Gets the value of the subCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubCode() {
        return subCode;
    }

    /**
     * Sets the value of the subCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubCode(String value) {
        this.subCode = value;
    }

    /**
     * Gets the value of the mid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMid() {
        return mid;
    }

    /**
     * Sets the value of the mid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMid(String value) {
        this.mid = value;
    }

    /**
     * Gets the value of the sid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSid() {
        return sid;
    }

    /**
     * Sets the value of the sid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSid(String value) {
        this.sid = value;
    }

    /**
     * Gets the value of the tid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTid() {
        return tid;
    }

    /**
     * Sets the value of the tid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTid(String value) {
        this.tid = value;
    }

    /**
     * Gets the value of the merchantType property.
     * 
     * @return
     *     possible object is
     *     {@link MerchantIdentifierType }
     *     
     */
    public MerchantIdentifierType getMerchantType() {
        return merchantType;
    }

    /**
     * Sets the value of the merchantType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchantIdentifierType }
     *     
     */
    public void setMerchantType(MerchantIdentifierType value) {
        this.merchantType = value;
    }

    /**
     * Gets the value of the merchantGenre property.
     * 
     * @return
     *     possible object is
     *     {@link MerchantGenreType }
     *     
     */
    public MerchantGenreType getMerchantGenre() {
        return merchantGenre;
    }

    /**
     * Sets the value of the merchantGenre property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchantGenreType }
     *     
     */
    public void setMerchantGenre(MerchantGenreType value) {
        this.merchantGenre = value;
    }

    /**
     * Gets the value of the onBoardingType property.
     * 
     * @return
     *     possible object is
     *     {@link MerchantOnBoardingType }
     *     
     */
    public MerchantOnBoardingType getOnBoardingType() {
        return onBoardingType;
    }

    /**
     * Sets the value of the onBoardingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchantOnBoardingType }
     *     
     */
    public void setOnBoardingType(MerchantOnBoardingType value) {
        this.onBoardingType = value;
    }

}
