//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.14 at 11:57:36 AM IST 
//


package com.npst.upiserver.npcischema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for refType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="refType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PAYER"/>
 *     &lt;enumeration value="PAYEE"/>
 *     &lt;enumeration value="CREDITADJUSTMENT"/>
 *     &lt;enumeration value="ONLINEREFUND"/>
 *     &lt;enumeration value="CHARGEBACK"/>
 *     &lt;enumeration value="PREARBITRATION"/>
 *     &lt;enumeration value="ARBITRATION"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "refType")
@XmlEnum
public enum RefType {

    PAYER,
    PAYEE,
    CREDITADJUSTMENT,
    ONLINEREFUND,
    CHARGEBACK,
    PREARBITRATION,
    ARBITRATION;

    public String value() {
        return name();
    }

    public static RefType fromValue(String v) {
        return valueOf(v);
    }

}
