package com.npst.upi.hor;

import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Complaint generated by hbm2java
 */
@Entity
@Table(name = "complaint", uniqueConstraints = @UniqueConstraint(columnNames = "TXNID"))
public class Complaint implements java.io.Serializable {

	/**
	 *
	 */

	private static final long serialVersionUID = 5943364296738002929L;
	private int bankAdjRefNo;
	private String mobileNo;
	private String virtualId;
	private String name;
	private String reasonCd;
	private String remark;
	private Date complaintDate;
	private String txndate;
	private String txnId;
	private String custRef;
	private String flag;
	private String adjAmount;
	private String status;
	private String pspStatus; // by
	// default
	// Pending
	private Timestamp txnTime;
	private String reasonCode;
	private int apiType;
	private String disputeType;

	public String getDisputeType() {
		return disputeType;
	}

	public void setDisputeType(String disputeType) {
		this.disputeType = disputeType;
	}

	public Complaint() {
	}

	public Complaint(int bankAdjRefNo, String mobileNo, String virtualId) {
		this.bankAdjRefNo = bankAdjRefNo;
		this.mobileNo = mobileNo;
		this.virtualId = virtualId;
	}

	public Complaint(int bankAdjRefNo, String mobileNo, String virtualId, String name, String reasonCd, String remark,
			Date complaintDate, String txndate, String txnId, String custRef, String flag, String adjAmount,
			String status, int apiType) {
		this.bankAdjRefNo = bankAdjRefNo;
		this.mobileNo = mobileNo;
		this.virtualId = virtualId;
		this.name = name;
		this.reasonCd = reasonCd;
		this.remark = remark;
		this.complaintDate = complaintDate;
		this.txndate = txndate;
		this.txnId = txnId;
		this.custRef = custRef;
		this.flag = flag;
		this.adjAmount = adjAmount;
		this.status = status;
		this.apiType = apiType;
	}

	@Column(name = "ADJAMOUNT", length = 10)
	public String getAdjAmount() {
		return this.adjAmount;
	}

	/**
	 * @return the apiType
	 */
	@Column(name = "APITYPE")
	public int getApiType() {
		return apiType;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "BANKADJREFNO", unique = true, nullable = false)
	public int getBankAdjRefNo() {
		return this.bankAdjRefNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "COMPLAINTDATE", length = 23)
	public Date getComplaintDate() {
		return this.complaintDate;
	}

	@Column(name = "CUSTREF", length = 15)
	public String getCustRef() {
		return this.custRef;
	}

	@Column(name = "FLAG", length = 5)
	public String getFlag() {
		return this.flag;
	}

	@Column(name = "MOBILENO", nullable = false, length = 12)
	public String getMobileNo() {
		return this.mobileNo;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public String getPspStatus() {
		return pspStatus;
	}

	@Column(name = "REASONCD", length = 5)
	public String getReasonCd() {
		return this.reasonCd;
	}

	public String getReasonCode() {
		return reasonCode;
	}

	@Column(name = "REMARK", length = 100)
	public String getRemark() {
		return this.remark;
	}

	@Column(name = "COMPSTATUS", length = 15)
	public String getStatus() {
		return this.status;
	}

	@Column(name = "TXNDATE")
	public String getTxndate() {
		return this.txndate;
	}

	@Column(name = "TXNID", unique = true, length = 35)
	public String getTxnId() {
		return this.txnId;
	}

	@Column(name = "TXNTIME")
	public Timestamp getTxnTime() {
		return txnTime;
	}

	@Column(name = "VIRTUALID", nullable = false, length = 50)
	public String getVirtualId() {
		return this.virtualId;
	}

	public void setAdjAmount(String adjAmount) {
		this.adjAmount = adjAmount;
	}

	/**
	 * @param apiType
	 *            the apiType to set
	 */
	public void setApiType(int apiType) {
		this.apiType = apiType;
	}

	public void setBankAdjRefNo(int bankAdjRefNo) {
		this.bankAdjRefNo = bankAdjRefNo;
	}

	public void setComplaintDate(Date complaintDate) {
		this.complaintDate = complaintDate;
	}

	public void setCustRef(String custRef) {
		this.custRef = custRef;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setPspStatus(String pspStatus) {
		this.pspStatus = pspStatus;
	}

	public void setReasonCd(String reasonCd) {
		this.reasonCd = reasonCd;
	}

	public void setReasonCode(String reasonCode) {
		this.reasonCode = reasonCode;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public void setTxndate(String txndate) {
		this.txndate = txndate;
	}

	public void setTxnId(String txnId) {
		this.txnId = txnId;
	}

	public void setTxnTime(Timestamp txnTime) {
		this.txnTime = txnTime;
	}

	public void setVirtualId(String virtualId) {
		this.virtualId = virtualId;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Complaint [bankAdjRefNo=");
		builder.append(bankAdjRefNo);
		builder.append(", ");
		if (mobileNo != null) {
			builder.append("mobileNo=");
			builder.append(mobileNo);
			builder.append(", ");
		}
		if (virtualId != null) {
			builder.append("virtualId=");
			builder.append(virtualId);
			builder.append(", ");
		}
		if (name != null) {
			builder.append("name=");
			builder.append(name);
			builder.append(", ");
		}
		if (reasonCd != null) {
			builder.append("reasonCd=");
			builder.append(reasonCd);
			builder.append(", ");
		}
		if (remark != null) {
			builder.append("remark=");
			builder.append(remark);
			builder.append(", ");
		}
		if (complaintDate != null) {
			builder.append("complaintDate=");
			builder.append(complaintDate);
			builder.append(", ");
		}
		if (txndate != null) {
			builder.append("txndate=");
			builder.append(txndate);
			builder.append(", ");
		}
		if (txnId != null) {
			builder.append("txnId=");
			builder.append(txnId);
			builder.append(", ");
		}
		if (custRef != null) {
			builder.append("custRef=");
			builder.append(custRef);
			builder.append(", ");
		}
		if (flag != null) {
			builder.append("flag=");
			builder.append(flag);
			builder.append(", ");
		}
		if (adjAmount != null) {
			builder.append("adjAmount=");
			builder.append(adjAmount);
			builder.append(", ");
		}
		if (status != null) {
			builder.append("status=");
			builder.append(status);
			builder.append(", ");
		}
		if (pspStatus != null) {
			builder.append("pspStatus=");
			builder.append(pspStatus);
			builder.append(", ");
		}
		if (txnTime != null) {
			builder.append("txnTime=");
			builder.append(txnTime);
			builder.append(", ");
		}
		if (reasonCode != null) {
			builder.append("reasonCode=");
			builder.append(reasonCode);
			builder.append(", ");
		}
		builder.append("]");
		return builder.toString();
	}

}
