//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2017.07.02 at 03:37:27 PM IST
//

package com.infosys.ci.fiusb.object;

import javax.xml.bind.annotation.XmlRegistry;


import com.npst.middleware.schema.AcctLienAddRequest;
import com.npst.middleware.schema.AcctLienAddRq;
import com.npst.middleware.schema.AcctLienAddRq.LienDtls.LienDt;
import com.npst.middleware.schema.AcctLienAddRq.LienDtls.NewLienAmt;





/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the generated package.
 * <p>
 * An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups. Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {
	
	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: generated
	 */
	public ObjectFactory() {
	}
	
	/**
	 * Create an instance of {@link ReqFixml }
	 */
	public ReqFixml createFIXML() {
		return new ReqFixml();
	}
	
	/**
	 * Create an instance of {@link ReqFixml.Body }
	 */
	public ReqFixml.Body createFIXMLBody() {
		return new ReqFixml.Body();
	}
	
	/**
	 * Create an instance of {@link ReqFixml.Body.ExecuteFinacleScriptRequest }
	 */
	public ReqFixml.Body.ExecuteFinacleScriptRequest createFIXMLBodyExecuteFinacleScriptRequest() {
		return new ReqFixml.Body.ExecuteFinacleScriptRequest();
	}
	
	/**
	 * Create an instance of
	 * {@link ReqFixml.Body.ExecuteFinacleScriptRequest.ExecuteFinacleScriptCustomData }
	 */
	public ReqFixml.Body.ExecuteFinacleScriptRequest.ExecuteFinacleScriptCustomData createFIXMLBodyExecuteFinacleScriptRequestExecuteFinacleScriptCustomData() {
		return new ReqFixml.Body.ExecuteFinacleScriptRequest.ExecuteFinacleScriptCustomData();
	}
	
	/**
	 * Create an instance of
	 * {@link ReqFixml.Body.ExecuteFinacleScriptRequest.ExecuteFinacleScriptInputVO }
	 */
	public ReqFixml.Body.ExecuteFinacleScriptRequest.ExecuteFinacleScriptInputVO createFIXMLBodyExecuteFinacleScriptRequestExecuteFinacleScriptInputVO() {
		return new ReqFixml.Body.ExecuteFinacleScriptRequest.ExecuteFinacleScriptInputVO();
	}
	
	/**
	 * Create an instance of {@link ReqFixml.Header }
	 */
	public ReqFixml.Header createFIXMLHeader() {
		return new ReqFixml.Header();
	}
	
	/**
	 * Create an instance of {@link ReqFixml.Header.RequestHeader }
	 */
	public ReqFixml.Header.RequestHeader createFIXMLHeaderRequestHeader() {
		return new ReqFixml.Header.RequestHeader();
	}
	
	/**
	 * Create an instance of {@link ReqFixml.Header.RequestHeader.MessageKey }
	 */
	public ReqFixml.Header.RequestHeader.MessageKey createFIXMLHeaderRequestHeaderMessageKey() {
		return new ReqFixml.Header.RequestHeader.MessageKey();
	}
	
	/**
	 * Create an instance of
	 * {@link ReqFixml.Header.RequestHeader.RequestMessageInfo }
	 */
	public ReqFixml.Header.RequestHeader.RequestMessageInfo createFIXMLHeaderRequestHeaderRequestMessageInfo() {
		return new ReqFixml.Header.RequestHeader.RequestMessageInfo();
	}
	
	/**
	 * Create an instance of {@link ReqFixml.Header.RequestHeader.Security }
	 */
	public ReqFixml.Header.RequestHeader.Security createFIXMLHeaderRequestHeaderSecurity() {
		return new ReqFixml.Header.RequestHeader.Security();
	}
	
	/**
	 * Create an instance of
	 * {@link ReqFixml.Header.RequestHeader.Security.Token }
	 */
	public ReqFixml.Header.RequestHeader.Security.Token createFIXMLHeaderRequestHeaderSecurityToken() {
		return new ReqFixml.Header.RequestHeader.Security.Token();
	}
	
	/**
	 * Create an instance of
	 * {@link ReqFixml.Header.RequestHeader.Security.Token.PasswordToken }
	 */
	public ReqFixml.Header.RequestHeader.Security.Token.PasswordToken createFIXMLHeaderRequestHeaderSecurityTokenPasswordToken() {
		return new ReqFixml.Header.RequestHeader.Security.Token.PasswordToken();
	}
	
	public RespFixml createRespFixml() {
		return new RespFixml();
	}
	
	/**
	 * Create an instance of {@link RespFixml.Body }
	 */
	public RespFixml.Body createRespFixmlBody() {
		return new RespFixml.Body();
	}
	
	/**
	 * Create an instance of
	 * {@link RespFixml.Body.ExecuteFinacleScriptResponse }
	 */
	public RespFixml.Body.ExecuteFinacleScriptResponse createRespFixmlBodyExecuteFinacleScriptResponse() {
		return new RespFixml.Body.ExecuteFinacleScriptResponse();
	}
	
	/**
	 * Create an instance of
	 * {@link RespFixml.Body.ExecuteFinacleScriptResponse.ExecuteFinacleScriptCustomData }
	 */
	public RespFixml.Body.ExecuteFinacleScriptResponse.ExecuteFinacleScriptCustomData createRespFixmlBodyExecuteFinacleScriptResponseExecuteFinacleScriptCustomData() {
		return new RespFixml.Body.ExecuteFinacleScriptResponse.ExecuteFinacleScriptCustomData();
	}
	
	/**
	 * Create an instance of
	 * {@link RespFixml.Body.ExecuteFinacleScriptResponse.ExecuteFinacleScriptCustomData.CustDet }
	 */
	public RespFixml.Body.ExecuteFinacleScriptResponse.ExecuteFinacleScriptCustomData.CustDet createRespFixmlBodyExecuteFinacleScriptResponseExecuteFinacleScriptCustomDataCustDet() {
		return new RespFixml.Body.ExecuteFinacleScriptResponse.ExecuteFinacleScriptCustomData.CustDet();
	}
	
	/**
	 * Create an instance of {@link RespFixml.Header }
	 */
	public RespFixml.Header createRespFixmlHeader() {
		return new RespFixml.Header();
	}
	
	/**
	 * Create an instance of {@link RespFixml.Header.ResponseHeader }
	 */
	public RespFixml.Header.ResponseHeader createRespFixmlHeaderResponseHeader() {
		return new RespFixml.Header.ResponseHeader();
	}
	
	/**
	 * Create an instance of
	 * {@link RespFixml.Header.ResponseHeader.HostParentTransaction }
	 */
	public RespFixml.Header.ResponseHeader.HostParentTransaction createRespFixmlHeaderResponseHeaderHostParentTransaction() {
		return new RespFixml.Header.ResponseHeader.HostParentTransaction();
	}
	
	/**
	 * Create an instance of
	 * {@link RespFixml.Header.ResponseHeader.HostTransaction }
	 */
	public RespFixml.Header.ResponseHeader.HostTransaction createRespFixmlHeaderResponseHeaderHostTransaction() {
		return new RespFixml.Header.ResponseHeader.HostTransaction();
	}
	
	/**
	 * Create an instance of
	 * {@link RespFixml.Header.ResponseHeader.RequestMessageKey }
	 */
	public RespFixml.Header.ResponseHeader.RequestMessageKey createRespFixmlHeaderResponseHeaderRequestMessageKey() {
		return new RespFixml.Header.ResponseHeader.RequestMessageKey();
	}
	
	/**
	 * Create an instance of
	 * {@link RespFixml.Header.ResponseHeader.ResponseMessageInfo }
	 */
	public RespFixml.Header.ResponseHeader.ResponseMessageInfo createRespFixmlHeaderResponseHeaderResponseMessageInfo() {
		return new RespFixml.Header.ResponseHeader.ResponseMessageInfo();
	}
	
	/**
	 * Create an instance of
	 * {@link RespFixml.Header.ResponseHeader.UBUSTransaction }
	 */
	public RespFixml.Header.ResponseHeader.UBUSTransaction createRespFixmlHeaderResponseHeaderUBUSTransaction() {
		return new RespFixml.Header.ResponseHeader.UBUSTransaction();
	}
	
	
	////
	
	
	public FIXMLResp createFIXMLResp() {
        return new FIXMLResp();
    }

    /**
     * Create an instance of {@link FIXMLResp.Body }
     * 
     */
    public FIXMLResp.Body createFIXMLRespBody() {
        return new FIXMLResp.Body();
    }

    /**
     * Create an instance of {@link FIXMLResp.Body.AcctLienAddResponse }
     * 
     */
    public FIXMLResp.Body.AcctLienAddResponse createFIXMLBodyAcctLienAddResponse() {
        return new FIXMLResp.Body.AcctLienAddResponse();
    }

    /**
     * Create an instance of {@link FIXMLResp.Body.AcctLienAddResponse.AcctLienAddRs }
     * 
     */
    public FIXMLResp.Body.AcctLienAddResponse.AcctLienAddRs createFIXMLBodyAcctLienAddResponseAcctLienAddRs() {
        return new FIXMLResp.Body.AcctLienAddResponse.AcctLienAddRs();
    }

    /**
     * Create an instance of {@link FIXMLResp.Body.AcctLienAddResponse.AcctLienAddRs.AcctId }
     * 
     */
    public FIXMLResp.Body.AcctLienAddResponse.AcctLienAddRs.AcctId createFIXMLBodyAcctLienAddResponseAcctLienAddRsAcctId() {
        return new FIXMLResp.Body.AcctLienAddResponse.AcctLienAddRs.AcctId();
    }

    /**
     * Create an instance of {@link FIXMLResp.Body.AcctLienAddResponse.AcctLienAddRs.AcctId.BankInfo }
     * 
     */
    public FIXMLResp.Body.AcctLienAddResponse.AcctLienAddRs.AcctId.BankInfo createFIXMLBodyAcctLienAddResponseAcctLienAddRsAcctIdBankInfo() {
        return new FIXMLResp.Body.AcctLienAddResponse.AcctLienAddRs.AcctId.BankInfo();
    }

    /**
     * Create an instance of {@link FIXMLResp.Header }
     * 
     */
    public FIXMLResp.Header createFIXMLRespHeader() {
        return new FIXMLResp.Header();
    }

    /**
     * Create an instance of {@link FIXMLResp.Header.ResponseHeader }
     * 
     */
    public FIXMLResp.Header.ResponseHeader createFIXMLRespHeaderResponseHeader() {
        return new FIXMLResp.Header.ResponseHeader();
    }

    /**
     * Create an instance of {@link FIXMLResp.Body.AcctLienAddResponse.AcctLienAddRs.LienIdRec }
     * 
     */
    public FIXMLResp.Body.AcctLienAddResponse.AcctLienAddRs.LienIdRec createFIXMLBodyAcctLienAddResponseAcctLienAddRsLienIdRec() {
        return new FIXMLResp.Body.AcctLienAddResponse.AcctLienAddRs.LienIdRec();
    }

    /**
     * Create an instance of {@link FIXMLResp.Body.AcctLienAddResponse.AcctLienAddRs.AcctId.AcctType }
     * 
     */
    public FIXMLResp.Body.AcctLienAddResponse.AcctLienAddRs.AcctId.AcctType createFIXMLBodyAcctLienAddResponseAcctLienAddRsAcctIdAcctType() {
        return new FIXMLResp.Body.AcctLienAddResponse.AcctLienAddRs.AcctId.AcctType();
    }

    /**
     * Create an instance of {@link FIXMLResp.Body.AcctLienAddResponse.AcctLienAddRs.AcctId.BankInfo.PostAddr }
     * 
     */
    public FIXMLResp.Body.AcctLienAddResponse.AcctLienAddRs.AcctId.BankInfo.PostAddr createFIXMLBodyAcctLienAddResponseAcctLienAddRsAcctIdBankInfoPostAddr() {
        return new FIXMLResp.Body.AcctLienAddResponse.AcctLienAddRs.AcctId.BankInfo.PostAddr();
    }

    /**
     * Create an instance of {@link FIXMLResp.Header.ResponseHeader.RequestMessageKey }
     * 
     */
    public FIXMLResp.Header.ResponseHeader.RequestMessageKey createFIXMLHeaderResponseHeaderRequestMessageKey() {
        return new FIXMLResp.Header.ResponseHeader.RequestMessageKey();
    }

    /**
     * Create an instance of {@link FIXMLResp.Header.ResponseHeader.ResponseMessageInfo }
     * 
     */
    public FIXMLResp.Header.ResponseHeader.ResponseMessageInfo createFIXMLHeaderResponseHeaderResponseMessageInfo() {
        return new FIXMLResp.Header.ResponseHeader.ResponseMessageInfo();
    }

    /**
     * Create an instance of {@link FIXMLResp.Header.ResponseHeader.UBUSTransaction }
     * 
     */
    public FIXMLResp.Header.ResponseHeader.UBUSTransaction createFIXMLHeaderResponseHeaderUBUSTransaction() {
        return new FIXMLResp.Header.ResponseHeader.UBUSTransaction();
    }

    /**
     * Create an instance of {@link FIXMLResp.Header.ResponseHeader.HostTransaction }
     * 
     */
    public FIXMLResp.Header.ResponseHeader.HostTransaction createFIXMLHeaderResponseHeaderHostTransaction() {
        return new FIXMLResp.Header.ResponseHeader.HostTransaction();
    }

    /**
     * Create an instance of {@link FIXMLResp.Header.ResponseHeader.HostParentTransaction }
     * 
     */
    public FIXMLResp.Header.ResponseHeader.HostParentTransaction createFIXMLHeaderResponseHeaderHostParentTransaction() {
        return new FIXMLResp.Header.ResponseHeader.HostParentTransaction();
    }

    public AcctLienAddRequest createFIXMLBodyAcctLienAddRequest(AcctLienAddRq acctLienAddRq) {
        return new AcctLienAddRequest( acctLienAddRq);
    }
    
    
    public AcctLienAddRq createFIXMLBodyAcctLienAddRequestAcctLienAddRq() {
        return new AcctLienAddRq(null, null, null);
    }

    /**
     * Create an instance of {@link FIXML.Body.AcctLienAddRequest.AcctLienAddRq.LienDtlss }
     * 
     */
    public AcctLienAddRq.LienDtls createFIXMLBodyAcctLienAddRequestAcctLienAddRqLienDtls(NewLienAmt newLienAmt, LienDt lienDt, String reasonCode) {
        return new AcctLienAddRq.LienDtls(newLienAmt,  lienDt,  reasonCode);
    }

    /**
     * Create an instance of {@link FIXML.Header }
     * 
     */
   

    /**
     * Create an instance of {@link FIXML.Header.RequestHeader }
     * 
     */
   

    /**
     * Create an instance of {@link FIXML.Header.RequestHeader.Security }
     * 
     */
  

    /**
     * Create an instance of {@link FIXML.Body.AcctLienAddRequest.AcctLienAddRq.AcctIds }
     * 
     */
    public AcctLienAddRq.AcctId createFIXMLBodyAcctLienAddRequestAcctLienAddRqAcctId() {
        return new AcctLienAddRq.AcctId();
    }

    /**
     * Create an instance of {@link NewLienAmts.Body.AcctLienAddRequest.AcctLienAddRq.LienDtlss.NewLienAmt }
     * 
     */
   
    public AcctLienAddRq.LienDtls.NewLienAmt createFIXMLBodyAcctLienAddRequestAcctLienAddRqLienDtlsNewLienAmt() {
        return new AcctLienAddRq.LienDtls.NewLienAmt();
    }
    /**
     * Create an instance of {@link LienDts.Body.AcctLienAddRequest.AcctLienAddRq.LienDtlss.LienDt }
     * 
     */
    public AcctLienAddRq.LienDtls.LienDt createFIXMLBodyAcctLienAddRequestAcctLienAddRqLienDtlsLienDt() {
        return new AcctLienAddRq.LienDtls.LienDt();
    }

    /**
     * Create an instance of {@link FIXML.Header.RequestHeader.MessageKey }
     * 
     */
    

    /**
     * Create an instance of {@link FIXML.Header.RequestHeader.RequestMessageInfo }
     * 
     */
   
    /**
     * Create an instance of {@link FIXML.Header.RequestHeader.Security.Token.PasswordToken }
     * 
     */
  


    /**
     * Create an instance of {@link FIXML.Header.RequestHeader }
     * 
     */
   

    /**
     * Create an instance of {@link FIXML.Header.RequestHeader.Security }
     * 
     */
  

    /**
     * Create an instance of {@link FIXML.Body.AcctLienAddRequest.AcctLienAddRq.AcctId }
     * 
     */
   

    /**
     * Create an instance of {@link NewLienAmts.Body.AcctLienAddRequest.AcctLienAddRq.LienDtlss.NewLienAmt }
     * 
     */
   
   
    
    //Mod Resp
    
    public FIXMLLienModResp createFIXMLLienModResp() {
        return new FIXMLLienModResp();
    }

    /**
     * Create an instance of {@link FIXMLLienModResp.Body }
     * 
     */
    public FIXMLLienModResp.Body createFIXMLLienModRespBody() {
        return new FIXMLLienModResp.Body();
    }

    /**
     * Create an instance of {@link FIXMLLienModResp.Body.AcctLienModResponse }
     * 
     */
    public FIXMLLienModResp.Body.AcctLienModResponse createFIXMLBodyAcctLienModResponse() {
        return new FIXMLLienModResp.Body.AcctLienModResponse();
    }

    /**
     * Create an instance of {@link FIXMLLienModResp.Body.AcctLienModResponse.AcctLienModRs }
     * 
     */
    public FIXMLLienModResp.Body.AcctLienModResponse.AcctLienModRs createFIXMLBodyAcctLienModResponseAcctLienModRs() {
        return new FIXMLLienModResp.Body.AcctLienModResponse.AcctLienModRs();
    }

    /**
     * Create an instance of {@link FIXMLLienModResp.Body.AcctLienModResponse.AcctLienModRs.AcctId }
     * 
     */
    public FIXMLLienModResp.Body.AcctLienModResponse.AcctLienModRs.AcctId createFIXMLBodyAcctLienModResponseAcctLienModRsAcctId() {
        return new FIXMLLienModResp.Body.AcctLienModResponse.AcctLienModRs.AcctId();
    }

    /**
     * Create an instance of {@link FIXMLLienModResp.Body.AcctLienModResponse.AcctLienModRs.AcctId.BankInfo }
     * 
     */
    public FIXMLLienModResp.Body.AcctLienModResponse.AcctLienModRs.AcctId.BankInfo createFIXMLBodyAcctLienModResponseAcctLienModRsAcctIdBankInfo() {
        return new FIXMLLienModResp.Body.AcctLienModResponse.AcctLienModRs.AcctId.BankInfo();
    }

    /**
     * Create an instance of {@link FIXMLLienModResp.Header }
     * 
     */
    public FIXMLLienModResp.Header createFIXMLLienModRespHeader() {
        return new FIXMLLienModResp.Header();
    }

    /**
     * Create an instance of {@link FIXMLLienModResp.Header.ResponseHeader }
     * 
     */
    public FIXMLLienModResp.Header.ResponseHeader createFIXMLHeaderResponseHeader() {
        return new FIXMLLienModResp.Header.ResponseHeader();
    }

    /**
     * Create an instance of {@link FIXMLLienModResp.Body.AcctLienModResponse.AcctLienModRs.LienIdRec }
     * 
     */
    public FIXMLLienModResp.Body.AcctLienModResponse.AcctLienModRs.LienIdRec createFIXMLBodyAcctLienModResponseAcctLienModRsLienIdRec() {
        return new FIXMLLienModResp.Body.AcctLienModResponse.AcctLienModRs.LienIdRec();
    }

    /**
     * Create an instance of {@link FIXMLLienModResp.Body.AcctLienModResponse.AcctLienModRs.AcctId.AcctType }
     * 
     */
    public FIXMLLienModResp.Body.AcctLienModResponse.AcctLienModRs.AcctId.AcctType createFIXMLBodyAcctLienModResponseAcctLienModRsAcctIdAcctType() {
        return new FIXMLLienModResp.Body.AcctLienModResponse.AcctLienModRs.AcctId.AcctType();
    }

    /**
     * Create an instance of {@link FIXMLLienModResp.Body.AcctLienModResponse.AcctLienModRs.AcctId.BankInfo.PostAddr }
     * 
     */
    public FIXMLLienModResp.Body.AcctLienModResponse.AcctLienModRs.AcctId.BankInfo.PostAddr createFIXMLBodyAcctLienModResponseAcctLienModRsAcctIdBankInfoPostAddr() {
        return new FIXMLLienModResp.Body.AcctLienModResponse.AcctLienModRs.AcctId.BankInfo.PostAddr();
    }

    /**
     * Create an instance of {@link FIXMLLienModResp.Header.ResponseHeader.RequestMessageKey }
     * 
     */
    public FIXMLLienModResp.Header.ResponseHeader.RequestMessageKey createFIXMLLienModRespHeaderResponseHeaderRequestMessageKey() {
        return new FIXMLLienModResp.Header.ResponseHeader.RequestMessageKey();
    }

    /**
     * Create an instance of {@link FIXMLLienModResp.Header.ResponseHeader.ResponseMessageInfo }
     * 
     */
    public FIXMLLienModResp.Header.ResponseHeader.ResponseMessageInfo createFIXMLLienModRespHeaderResponseHeaderResponseMessageInfo() {
        return new FIXMLLienModResp.Header.ResponseHeader.ResponseMessageInfo();
    }

    /**
     * Create an instance of {@link FIXMLLienModResp.Header.ResponseHeader.UBUSTransaction }
     * 
     */
    public FIXMLLienModResp.Header.ResponseHeader.UBUSTransaction createFIXMLLienModRespHeaderResponseHeaderUBUSTransaction() {
        return new FIXMLLienModResp.Header.ResponseHeader.UBUSTransaction();
    }

    /**
     * Create an instance of {@link FIXMLLienModResp.Header.ResponseHeader.HostTransaction }
     * 
     */
    public FIXMLLienModResp.Header.ResponseHeader.HostTransaction createFIXMLLienModRespHeaderResponseHeaderHostTransaction() {
        return new FIXMLLienModResp.Header.ResponseHeader.HostTransaction();
    }

    /**
     * Create an instance of {@link FIXMLLienModResp.Header.ResponseHeader.HostParentTransaction }
     * 
     */
    public FIXMLLienModResp.Header.ResponseHeader.HostParentTransaction createFIXMLLienModRespHeaderResponseHeaderHostParentTransaction() {
        return new FIXMLLienModResp.Header.ResponseHeader.HostParentTransaction();
    }
//Inq Response
    
    public FIXMLLienInqResp createFIXMLLienInqResp() {
        return new FIXMLLienInqResp();
    }

    /**
     * Create an instance of {@link FIXMLLienInqResp.Body }
     * 
     */
    public FIXMLLienInqResp.Body createFIXMLLienInqRespBody() {
        return new FIXMLLienInqResp.Body();
    }

    /**
     * Create an instance of {@link FIXMLLienInqResp.Body.AcctLienInqResponse }
     * 
     */
    public FIXMLLienInqResp.Body.AcctLienInqResponse createFIXMLBodyAcctLienInqResponse() {
        return new FIXMLLienInqResp.Body.AcctLienInqResponse();
    }

    /**
     * Create an instance of {@link FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs }
     * 
     */
    public FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs createFIXMLBodyAcctLienInqResponseAcctLienInqRs() {
        return new FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs();
    }

    /**
     * Create an instance of {@link FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.LienDtlsRec }
     * 
     */
    public FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.LienDtlsRec createFIXMLBodyAcctLienInqResponseAcctLienInqRsLienDtlsRec() {
        return new FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.LienDtlsRec();
    }

    /**
     * Create an instance of {@link FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.AcctId }
     * 
     */
    public FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.AcctId createFIXMLBodyAcctLienInqResponseAcctLienInqRsAcctId() {
        return new FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.AcctId();
    }

    /**
     * Create an instance of {@link FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.AcctId.BankInfo }
     * 
     */
    public FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.AcctId.BankInfo createFIXMLBodyAcctLienInqResponseAcctLienInqRsAcctIdBankInfo() {
        return new FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.AcctId.BankInfo();
    }

    /**
     * Create an instance of {@link FIXMLLienInqResp.Header }
     * 
     */
    public FIXMLLienInqResp.Header createFIXMLLienInqRespHeader() {
        return new FIXMLLienInqResp.Header();
    }

    /**
     * Create an instance of {@link FIXMLLienInqResp.Header.ResponseHeader }
     * 
     */
    public FIXMLLienInqResp.Header.ResponseHeader createFIXMLLienInqRespHeaderResponseHeader() {
        return new FIXMLLienInqResp.Header.ResponseHeader();
    }

    /**
     * Create an instance of {@link FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.LienDtlsRec.NewLienAmt }
     * 
     */
    public FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.LienDtlsRec.NewLienAmt createFIXMLBodyAcctLienInqResponseAcctLienInqRsLienDtlsRecNewLienAmt() {
        return new FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.LienDtlsRec.NewLienAmt();
    }

    /**
     * Create an instance of {@link FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.LienDtlsRec.OldLienAmt }
     * 
     */
    public FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.LienDtlsRec.OldLienAmt createFIXMLBodyAcctLienInqResponseAcctLienInqRsLienDtlsRecOldLienAmt() {
        return new FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.LienDtlsRec.OldLienAmt();
    }

    /**
     * Create an instance of {@link FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.LienDtlsRec.LienDt }
     * 
     */
    public FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.LienDtlsRec.LienDt createFIXMLBodyAcctLienInqResponseAcctLienInqRsLienDtlsRecLienDt() {
        return new FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.LienDtlsRec.LienDt();
    }

    /**
     * Create an instance of {@link FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.AcctId.AcctType }
     * 
     */
    public FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.AcctId.AcctType createFIXMLBodyAcctLienInqResponseAcctLienInqRsAcctIdAcctType() {
        return new FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.AcctId.AcctType();
    }

    /**
     * Create an instance of {@link FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.AcctId.BankInfo.PostAddr }
     * 
     */
    public FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.AcctId.BankInfo.PostAddr createFIXMLBodyAcctLienInqResponseAcctLienInqRsAcctIdBankInfoPostAddr() {
        return new FIXMLLienInqResp.Body.AcctLienInqResponse.AcctLienInqRs.AcctId.BankInfo.PostAddr();
    }

    /**
     * Create an instance of {@link FIXMLLienInqResp.Header.ResponseHeader.RequestMessageKey }
     * 
     */
    public FIXMLLienInqResp.Header.ResponseHeader.RequestMessageKey createFIXMLLienInqRespHeaderResponseHeaderRequestMessageKey() {
        return new FIXMLLienInqResp.Header.ResponseHeader.RequestMessageKey();
    }

    /**
     * Create an instance of {@link FIXMLLienInqResp.Header.ResponseHeader.ResponseMessageInfo }
     * 
     */
    public FIXMLLienInqResp.Header.ResponseHeader.ResponseMessageInfo createFIXMLLienInqRespHeaderResponseHeaderResponseMessageInfo() {
        return new FIXMLLienInqResp.Header.ResponseHeader.ResponseMessageInfo();
    }

    /**
     * Create an instance of {@link FIXMLLienInqResp.Header.ResponseHeader.UBUSTransaction }
     * 
     */
    public FIXMLLienInqResp.Header.ResponseHeader.UBUSTransaction createFIXMLLienInqRespHeaderResponseHeaderUBUSTransaction() {
        return new FIXMLLienInqResp.Header.ResponseHeader.UBUSTransaction();
    }

    /**
     * Create an instance of {@link FIXMLLienInqResp.Header.ResponseHeader.HostTransaction }
     * 
     */
    public FIXMLLienInqResp.Header.ResponseHeader.HostTransaction createFIXMLLienInqRespHeaderResponseHeaderHostTransaction() {
        return new FIXMLLienInqResp.Header.ResponseHeader.HostTransaction();
    }

    /**
     * Create an instance of {@link FIXMLLienInqResp.Header.ResponseHeader.HostParentTransaction }
     * 
     */
    public FIXMLLienInqResp.Header.ResponseHeader.HostParentTransaction createFIXMLLienInqRespHeaderResponseHeaderHostParentTransaction() {
        return new FIXMLLienInqResp.Header.ResponseHeader.HostParentTransaction();
    }

//Inq Error
    
    public FIXMLLienInqResp.Body.Error createFIXMLBodyError() {
        return new FIXMLLienInqResp.Body.Error();
    }

    /**
     * Create an instance of {@link FIXMLLienInqResp.Body.Error.FIBusinessException }
     * 
     */
    public FIXMLLienInqResp.Body.Error.FIBusinessException createFIXMLBodyErrorFIBusinessException() {
        return new FIXMLLienInqResp.Body.Error.FIBusinessException();
    }

   

 /**
     * Create an instance of {@link FIXMLLienInqResp.Body.Error.FIBusinessException.ErrorDetail }
     * 
     */
    public FIXMLLienInqResp.Body.Error.FIBusinessException.ErrorDetail createFIXMLBodyErrorFIBusinessExceptionErrorDetail() {
        return new FIXMLLienInqResp.Body.Error.FIBusinessException.ErrorDetail();
    }

}
