//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.14 at 11:57:36 AM IST 
//


package com.npst.upiserver.npcischema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.npci.upi.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.npci.upi.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CredsType.Cred.Data }
     * 
     */
    public CredsType.Cred.Data createCredsTypeCredData() {
        return new CredsType.Cred.Data();
    }

    /**
     * Create an instance of {@link PayerType }
     * 
     */
    public PayerType createPayerType() {
        return new PayerType();
    }

    /**
     * Create an instance of {@link TxnConfDtl }
     * 
     */
    public TxnConfDtl createTxnConfDtl() {
        return new TxnConfDtl();
    }

    /**
     * Create an instance of {@link MandateType.Amount }
     * 
     */
    public MandateType.Amount createMandateTypeAmount() {
        return new MandateType.Amount();
    }

    /**
     * Create an instance of {@link IdentityType }
     * 
     */
    public IdentityType createIdentityType() {
        return new IdentityType();
    }

    /**
     * Create an instance of {@link HeadType }
     * 
     */
    public HeadType createHeadType() {
        return new HeadType();
    }

    /**
     * Create an instance of {@link InstitutionOriginator }
     * 
     */
    public InstitutionOriginator createInstitutionOriginator() {
        return new InstitutionOriginator();
    }

    /**
     * Create an instance of {@link InstitutionOriginatorAddress }
     * 
     */
    public InstitutionOriginatorAddress createInstitutionOriginatorAddress() {
        return new InstitutionOriginatorAddress();
    }

    /**
     * Create an instance of {@link PayeeType }
     * 
     */
    public PayeeType createPayeeType() {
        return new PayeeType();
    }

    /**
     * Create an instance of {@link PspVersionSupportedType }
     * 
     */
    public PspVersionSupportedType createPspVersionSupportedType() {
        return new PspVersionSupportedType();
    }

    /**
     * Create an instance of {@link IdentifierType }
     * 
     */
    public IdentifierType createIdentifierType() {
        return new IdentifierType();
    }

    /**
     * Create an instance of {@link RulesType.Rule }
     * 
     */
    public RulesType.Rule createRulesTypeRule() {
        return new RulesType.Rule();
    }

    /**
     * Create an instance of {@link InstitutionBeneficiary }
     * 
     */
    public InstitutionBeneficiary createInstitutionBeneficiary() {
        return new InstitutionBeneficiary();
    }

    /**
     * Create an instance of {@link MerchantOwnership }
     * 
     */
    public MerchantOwnership createMerchantOwnership() {
        return new MerchantOwnership();
    }

    /**
     * Create an instance of {@link MetaType }
     * 
     */
    public MetaType createMetaType() {
        return new MetaType();
    }

    /**
     * Create an instance of {@link CredsAllowedType }
     * 
     */
    public CredsAllowedType createCredsAllowedType() {
        return new CredsAllowedType();
    }

    /**
     * Create an instance of {@link RespVaeRef }
     * 
     */
    public RespVaeRef createRespVaeRef() {
        return new RespVaeRef();
    }

    /**
     * Create an instance of {@link RecurrenceType.Rule }
     * 
     */
    public RecurrenceType.Rule createRecurrenceTypeRule() {
        return new RecurrenceType.Rule();
    }

    /**
     * Create an instance of {@link InfoType }
     * 
     */
    public InfoType createInfoType() {
        return new InfoType();
    }

    /**
     * Create an instance of {@link RespTypeValAddr }
     * 
     */
    public RespTypeValAddr createRespTypeValAddr() {
        return new RespTypeValAddr();
    }

    /**
     * Create an instance of {@link RulesType }
     * 
     */
    public RulesType createRulesType() {
        return new RulesType();
    }

    /**
     * Create an instance of {@link InstitutionPurpose }
     * 
     */
    public InstitutionPurpose createInstitutionPurpose() {
        return new InstitutionPurpose();
    }

    /**
     * Create an instance of {@link MerchantType }
     * 
     */
    public MerchantType createMerchantType() {
        return new MerchantType();
    }

    /**
     * Create an instance of {@link AmountType.Split }
     * 
     */
    public AmountType.Split createAmountTypeSplit() {
        return new AmountType.Split();
    }

    /**
     * Create an instance of {@link InstitutionName }
     * 
     */
    public InstitutionName createInstitutionName() {
        return new InstitutionName();
    }

    /**
     * Create an instance of {@link Ref }
     * 
     */
    public Ref createRef() {
        return new Ref();
    }

    /**
     * Create an instance of {@link MandateSign }
     * 
     */
    public MandateSign createMandateSign() {
        return new MandateSign();
    }

    /**
     * Create an instance of {@link AccountType.Detail }
     * 
     */
    public AccountType.Detail createAccountTypeDetail() {
        return new AccountType.Detail();
    }

    /**
     * Create an instance of {@link DeviceType }
     * 
     */
    public DeviceType createDeviceType() {
        return new DeviceType();
    }

    /**
     * Create an instance of {@link RecurrenceType }
     * 
     */
    public RecurrenceType createRecurrenceType() {
        return new RecurrenceType();
    }

    /**
     * Create an instance of {@link KeyType }
     * 
     */
    public KeyType createKeyType() {
        return new KeyType();
    }

    /**
     * Create an instance of {@link MandateType }
     * 
     */
    public MandateType createMandateType() {
        return new MandateType();
    }

    /**
     * Create an instance of {@link MandateType.Validity }
     * 
     */
    public MandateType.Validity createMandateTypeValidity() {
        return new MandateType.Validity();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link RiskScoresType.Score }
     * 
     */
    public RiskScoresType.Score createRiskScoresTypeScore() {
        return new RiskScoresType.Score();
    }

    /**
     * Create an instance of {@link CredsType.Cred }
     * 
     */
    public CredsType.Cred createCredsTypeCred() {
        return new CredsType.Cred();
    }

    /**
     * Create an instance of {@link AccountType }
     * 
     */
    public AccountType createAccountType() {
        return new AccountType();
    }

    /**
     * Create an instance of {@link FeatureSupportedType }
     * 
     */
    public FeatureSupportedType createFeatureSupportedType() {
        return new FeatureSupportedType();
    }

    /**
     * Create an instance of {@link InstitutionType }
     * 
     */
    public InstitutionType createInstitutionType() {
        return new InstitutionType();
    }

    /**
     * Create an instance of {@link PayeesType }
     * 
     */
    public PayeesType createPayeesType() {
        return new PayeesType();
    }

    /**
     * Create an instance of {@link CredsType }
     * 
     */
    public CredsType createCredsType() {
        return new CredsType();
    }

    /**
     * Create an instance of {@link RespType }
     * 
     */
    public RespType createRespType() {
        return new RespType();
    }

    /**
     * Create an instance of {@link RatingType }
     * 
     */
    public RatingType createRatingType() {
        return new RatingType();
    }

    /**
     * Create an instance of {@link AmountType }
     * 
     */
    public AmountType createAmountType() {
        return new AmountType();
    }

    /**
     * Create an instance of {@link PspVersionType }
     * 
     */
    public PspVersionType createPspVersionType() {
        return new PspVersionType();
    }

    /**
     * Create an instance of {@link DeviceType.Tag }
     * 
     */
    public DeviceType.Tag createDeviceTypeTag() {
        return new DeviceType.Tag();
    }

    /**
     * Create an instance of {@link RiskScoresType }
     * 
     */
    public RiskScoresType createRiskScoresType() {
        return new RiskScoresType();
    }

    /**
     * Create an instance of {@link PayTrans }
     * 
     */
    public PayTrans createPayTrans() {
        return new PayTrans();
    }

}
