//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2017.08.09 at 01:53:13 PM IST
//

package com.npst.middleware.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ExecuteFinacleScriptInputVOType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ExecuteFinacleScriptInputVOType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExecuteFinacleScriptInputVOType", propOrder = {
		"requestId"
})
public class ExecuteFinacleScriptInputVOType {
	
	@XmlElement(required = true)
	protected String requestId;
	
	public ExecuteFinacleScriptInputVOType() {
		super();
	}
	
	public ExecuteFinacleScriptInputVOType(String requestId) {
		super();
		this.requestId = requestId;
	}
	
	/**
	 * Gets the value of the requestId property.
	 *
	 * @return
	 * 		possible object is
	 *         {@link String }
	 */
	public String getRequestId() {
		return requestId;
	}
	
	/**
	 * Sets the value of the requestId property.
	 *
	 * @param value
	 *            allowed object is
	 *            {@link String }
	 */
	public void setRequestId(String value) {
		this.requestId = value;
	}
	
}
