//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2017.08.09 at 01:53:13 PM IST
//

package com.npst.middleware.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.npst.schema package.
 * <p>
 * An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups. Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {
	
	private final static QName _FIXML_QNAME = new QName("http://www.finacle.com/fixml", "FIXML");
	
	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: com.npst.schema
	 */
	public ObjectFactory() {
	}
	
	/**
	 * Create an instance of {@link BodyType }
	 */
	public BodyType createBodyType() {
		return new BodyType();
	}
	
	/**
	 * Create an instance of {@link ExecuteFinacleScriptCustomDataType }
	 */
	public ExecuteFinacleScriptCustomDataType createExecuteFinacleScriptCustomDataType() {
		return new ExecuteFinacleScriptCustomDataType();
	}
	
	/**
	 * Create an instance of {@link ExecuteFinacleScriptInputVOType }
	 */
	public ExecuteFinacleScriptInputVOType createExecuteFinacleScriptInputVOType() {
		return new ExecuteFinacleScriptInputVOType();
	}
	
	/**
	 * Create an instance of {@link ExecuteFinacleScriptRequestType }
	 */
	public ExecuteFinacleScriptRequestType createExecuteFinacleScriptRequestType() {
		return new ExecuteFinacleScriptRequestType();
	}
	
	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link FIXMLType
	 * }{@code >}}
	 */
	@XmlElementDecl(namespace = "http://www.finacle.com/fixml", name = "FIXML")
	public JAXBElement<FIXMLType> createFIXML(FIXMLType value) {
		return new JAXBElement<FIXMLType>(_FIXML_QNAME, FIXMLType.class, null, value);
	}
	
	/**
	 * Create an instance of {@link FIXMLType }
	 */
	public FIXMLType createFIXMLType() {
		return new FIXMLType();
	}
	
	/**
	 * Create an instance of {@link HeaderType }
	 */
	public HeaderType createHeaderType() {
		return new HeaderType();
	}
	
	/**
	 * Create an instance of {@link MessageKeyType }
	 */
	public MessageKeyType createMessageKeyType() {
		return new MessageKeyType();
	}
	
	/**
	 * Create an instance of {@link PasswordTokenType }
	 */
	public PasswordTokenType createPasswordTokenType() {
		return new PasswordTokenType();
	}
	
	/**
	 * Create an instance of {@link RequestHeaderType }
	 */
	public RequestHeaderType createRequestHeaderType() {
		return new RequestHeaderType();
	}
	
	/**
	 * Create an instance of {@link RequestMessageInfoType }
	 */
	public RequestMessageInfoType createRequestMessageInfoType() {
		return new RequestMessageInfoType();
	}
	
	/**
	 * Create an instance of {@link SecurityType }
	 */
	public SecurityType createSecurityType() {
		return new SecurityType();
	}
	
	/**
	 * Create an instance of {@link TokenType }
	 */
	public TokenType createTokenType() {
		return new TokenType();
	}
	
}
