//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2017.08.09 at 01:53:13 PM IST
//

package com.npst.middleware.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for RequestHeaderType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="RequestHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageKey" type="{http://www.finacle.com/fixml}MessageKeyType"/>
 *         &lt;element name="RequestMessageInfo" type="{http://www.finacle.com/fixml}RequestMessageInfoType"/>
 *         &lt;element name="Security" type="{http://www.finacle.com/fixml}SecurityType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestHeaderType", propOrder = {
		"messageKey", "requestMessageInfo", "security"
})
public class RequestHeaderType {
	
	@XmlElement(name = "MessageKey", required = true)
	protected MessageKeyType			messageKey;
	@XmlElement(name = "RequestMessageInfo", required = true)
	protected RequestMessageInfoType	requestMessageInfo;
	@XmlElement(name = "Security", required = true)
	protected SecurityType				security;
	
	public RequestHeaderType() {
		super();
	}
	
	public RequestHeaderType(MessageKeyType messageKey, RequestMessageInfoType requestMessageInfo,
			SecurityType security) {
		super();
		this.messageKey = messageKey;
		this.requestMessageInfo = requestMessageInfo;
		this.security = security;
	}
	
	/**
	 * Gets the value of the messageKey property.
	 *
	 * @return
	 * 		possible object is
	 *         {@link MessageKeyType }
	 */
	public MessageKeyType getMessageKey() {
		return messageKey;
	}
	
	/**
	 * Gets the value of the requestMessageInfo property.
	 *
	 * @return
	 * 		possible object is
	 *         {@link RequestMessageInfoType }
	 */
	public RequestMessageInfoType getRequestMessageInfo() {
		return requestMessageInfo;
	}
	
	/**
	 * Gets the value of the security property.
	 *
	 * @return
	 * 		possible object is
	 *         {@link SecurityType }
	 */
	public SecurityType getSecurity() {
		return security;
	}
	
	/**
	 * Sets the value of the messageKey property.
	 *
	 * @param value
	 *            allowed object is
	 *            {@link MessageKeyType }
	 */
	public void setMessageKey(MessageKeyType value) {
		this.messageKey = value;
	}
	
	/**
	 * Sets the value of the requestMessageInfo property.
	 *
	 * @param value
	 *            allowed object is
	 *            {@link RequestMessageInfoType }
	 */
	public void setRequestMessageInfo(RequestMessageInfoType value) {
		this.requestMessageInfo = value;
	}
	
	/**
	 * Sets the value of the security property.
	 *
	 * @param value
	 *            allowed object is
	 *            {@link SecurityType }
	 */
	public void setSecurity(SecurityType value) {
		this.security = value;
	}
	
}
