//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2017.08.09 at 01:53:13 PM IST
//

package com.npst.middleware.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for TokenType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="TokenType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PasswordToken" type="{http://www.finacle.com/fixml}PasswordTokenType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TokenType", propOrder = {
		"passwordToken"
})
public class TokenType {
	
	@XmlElement(name = "PasswordToken", required = true)
	protected PasswordTokenType passwordToken;
	
	public TokenType() {
		super();
	}
	
	public TokenType(PasswordTokenType passwordToken) {
		super();
		this.passwordToken = passwordToken;
	}
	
	/**
	 * Gets the value of the passwordToken property.
	 *
	 * @return
	 * 		possible object is
	 *         {@link PasswordTokenType }
	 */
	public PasswordTokenType getPasswordToken() {
		return passwordToken;
	}
	
	/**
	 * Sets the value of the passwordToken property.
	 *
	 * @param value
	 *            allowed object is
	 *            {@link PasswordTokenType }
	 */
	public void setPasswordToken(PasswordTokenType value) {
		this.passwordToken = value;
	}
	
}
