//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2017.07.02 at 03:37:27 PM IST
//

package com.infosys.ci.fiusb.object;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RequestHeader">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="MessageKey">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="LanguageId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="RequestMessageInfo">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="EntityId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="EntityType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="ArmCorrelationId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Security">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Token">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="PasswordToken">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                                           &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="FICertToken" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="RealUserLoginSessionId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="RealUser" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="RealUserPwd" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="SSOTransferToken" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Body">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="executeFinacleScriptRequest">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ExecuteFinacleScriptInputVO">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="requestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="executeFinacleScript_CustomData">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="MOBILENO" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"header", "body"
})
@XmlRootElement(name = "FIXML")
public class ReqFixml {
	
	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="executeFinacleScriptRequest">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="ExecuteFinacleScriptInputVO">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="requestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="executeFinacleScript_CustomData">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="MOBILENO" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"executeFinacleScriptRequest"
	})
	public static class Body {
		
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="ExecuteFinacleScriptInputVO">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="requestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="executeFinacleScript_CustomData">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="MOBILENO" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"executeFinacleScriptInputVO", "executeFinacleScriptCustomData"
		})
		public static class ExecuteFinacleScriptRequest {
			
			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 *
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="MOBILENO" type="{http://www.w3.org/2001/XMLSchema}int"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = {
					"mobileno"
			})
			public static class ExecuteFinacleScriptCustomData {
				
				@XmlElement(name = "MOBILENO")
				protected int mobileno;
				
				/**
				 * Gets the value of the mobileno property.
				 */
				public int getMOBILENO() {
					return mobileno;
				}
				
				/**
				 * Sets the value of the mobileno property.
				 */
				public void setMOBILENO(int value) {
					this.mobileno = value;
				}
				
			}
			
			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 *
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="requestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = {
					"requestId"
			})
			public static class ExecuteFinacleScriptInputVO {
				
				@XmlElement(required = true)
				protected String requestId;
				
				/**
				 * Gets the value of the requestId property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link String }
				 */
				public String getRequestId() {
					return requestId;
				}
				
				/**
				 * Sets the value of the requestId property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link String }
				 */
				public void setRequestId(String value) {
					this.requestId = value;
				}
				
			}
			
			@XmlElement(name = "ExecuteFinacleScriptInputVO", required = true)
			protected ReqFixml.Body.ExecuteFinacleScriptRequest.ExecuteFinacleScriptInputVO		executeFinacleScriptInputVO;
			
			@XmlElement(name = "executeFinacleScript_CustomData", required = true)
			protected ReqFixml.Body.ExecuteFinacleScriptRequest.ExecuteFinacleScriptCustomData	executeFinacleScriptCustomData;
			
			/**
			 * Gets the value of the executeFinacleScriptCustomData property.
			 *
			 * @return
			 * 		possible object is
			 *         {@link ReqFixml.Body.ExecuteFinacleScriptRequest.ExecuteFinacleScriptCustomData }
			 */
			public ReqFixml.Body.ExecuteFinacleScriptRequest.ExecuteFinacleScriptCustomData getExecuteFinacleScriptCustomData() {
				return executeFinacleScriptCustomData;
			}
			
			/**
			 * Gets the value of the executeFinacleScriptInputVO property.
			 *
			 * @return
			 * 		possible object is
			 *         {@link ReqFixml.Body.ExecuteFinacleScriptRequest.ExecuteFinacleScriptInputVO }
			 */
			public ReqFixml.Body.ExecuteFinacleScriptRequest.ExecuteFinacleScriptInputVO getExecuteFinacleScriptInputVO() {
				return executeFinacleScriptInputVO;
			}
			
			/**
			 * Sets the value of the executeFinacleScriptCustomData property.
			 *
			 * @param value
			 *            allowed object is
			 *            {@link ReqFixml.Body.ExecuteFinacleScriptRequest.ExecuteFinacleScriptCustomData }
			 */
			public void setExecuteFinacleScriptCustomData(
					ReqFixml.Body.ExecuteFinacleScriptRequest.ExecuteFinacleScriptCustomData value) {
				this.executeFinacleScriptCustomData = value;
			}
			
			/**
			 * Sets the value of the executeFinacleScriptInputVO property.
			 *
			 * @param value
			 *            allowed object is
			 *            {@link ReqFixml.Body.ExecuteFinacleScriptRequest.ExecuteFinacleScriptInputVO }
			 */
			public void setExecuteFinacleScriptInputVO(
					ReqFixml.Body.ExecuteFinacleScriptRequest.ExecuteFinacleScriptInputVO value) {
				this.executeFinacleScriptInputVO = value;
			}
			
		}
		
		@XmlElement(required = true)
		protected ReqFixml.Body.ExecuteFinacleScriptRequest executeFinacleScriptRequest;
		
		/**
		 * Gets the value of the executeFinacleScriptRequest property.
		 *
		 * @return
		 * 		possible object is
		 *         {@link ReqFixml.Body.ExecuteFinacleScriptRequest }
		 */
		public ReqFixml.Body.ExecuteFinacleScriptRequest getExecuteFinacleScriptRequest() {
			return executeFinacleScriptRequest;
		}
		
		/**
		 * Sets the value of the executeFinacleScriptRequest property.
		 *
		 * @param value
		 *            allowed object is
		 *            {@link ReqFixml.Body.ExecuteFinacleScriptRequest }
		 */
		public void setExecuteFinacleScriptRequest(ReqFixml.Body.ExecuteFinacleScriptRequest value) {
			this.executeFinacleScriptRequest = value;
		}
		
	}
	
	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="RequestHeader">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="MessageKey">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                             &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                             &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}double"/>
	 *                             &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                             &lt;element name="LanguageId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="RequestMessageInfo">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                             &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                             &lt;element name="EntityId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                             &lt;element name="EntityType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                             &lt;element name="ArmCorrelationId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                             &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="Security">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="Token">
	 *                               &lt;complexType>
	 *                                 &lt;complexContent>
	 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                     &lt;sequence>
	 *                                       &lt;element name="PasswordToken">
	 *                                         &lt;complexType>
	 *                                           &lt;complexContent>
	 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                               &lt;sequence>
	 *                                                 &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                                                 &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                                               &lt;/sequence>
	 *                                             &lt;/restriction>
	 *                                           &lt;/complexContent>
	 *                                         &lt;/complexType>
	 *                                       &lt;/element>
	 *                                     &lt;/sequence>
	 *                                   &lt;/restriction>
	 *                                 &lt;/complexContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                             &lt;element name="FICertToken" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                             &lt;element name="RealUserLoginSessionId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                             &lt;element name="RealUser" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                             &lt;element name="RealUserPwd" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                             &lt;element name="SSOTransferToken" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"requestHeader"
	})
	public static class Header {
		
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="MessageKey">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                   &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                   &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}double"/>
		 *                   &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                   &lt;element name="LanguageId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="RequestMessageInfo">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *                   &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *                   &lt;element name="EntityId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *                   &lt;element name="EntityType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *                   &lt;element name="ArmCorrelationId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *                   &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="Security">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="Token">
		 *                     &lt;complexType>
		 *                       &lt;complexContent>
		 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                           &lt;sequence>
		 *                             &lt;element name="PasswordToken">
		 *                               &lt;complexType>
		 *                                 &lt;complexContent>
		 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                                     &lt;sequence>
		 *                                       &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *                                       &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *                                     &lt;/sequence>
		 *                                   &lt;/restriction>
		 *                                 &lt;/complexContent>
		 *                               &lt;/complexType>
		 *                             &lt;/element>
		 *                           &lt;/sequence>
		 *                         &lt;/restriction>
		 *                       &lt;/complexContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                   &lt;element name="FICertToken" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *                   &lt;element name="RealUserLoginSessionId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *                   &lt;element name="RealUser" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *                   &lt;element name="RealUserPwd" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *                   &lt;element name="SSOTransferToken" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"messageKey", "requestMessageInfo", "security"
		})
		public static class RequestHeader {
			
			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 *
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *         &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *         &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}double"/>
			 *         &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *         &lt;element name="LanguageId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = {
					"requestUUID", "serviceRequestId", "serviceRequestVersion", "channelId", "languageId"
			})
			public static class MessageKey {
				
				@XmlElement(name = "RequestUUID", required = true)
				protected String	requestUUID;
				@XmlElement(name = "ServiceRequestId", required = true)
				protected String	serviceRequestId;
				@XmlElement(name = "ServiceRequestVersion")
				protected double	serviceRequestVersion;
				@XmlElement(name = "ChannelId", required = true)
				protected String	channelId;
				@XmlElement(name = "LanguageId", required = true)
				protected Object	languageId;
				
				/**
				 * Gets the value of the channelId property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link String }
				 */
				public String getChannelId() {
					return channelId;
				}
				
				/**
				 * Gets the value of the languageId property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link Object }
				 */
				public Object getLanguageId() {
					return languageId;
				}
				
				/**
				 * Gets the value of the requestUUID property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link String }
				 */
				public String getRequestUUID() {
					return requestUUID;
				}
				
				/**
				 * Gets the value of the serviceRequestId property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link String }
				 */
				public String getServiceRequestId() {
					return serviceRequestId;
				}
				
				/**
				 * Gets the value of the serviceRequestVersion property.
				 */
				public double getServiceRequestVersion() {
					return serviceRequestVersion;
				}
				
				/**
				 * Sets the value of the channelId property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link String }
				 */
				public void setChannelId(String value) {
					this.channelId = value;
				}
				
				/**
				 * Sets the value of the languageId property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link Object }
				 */
				public void setLanguageId(Object value) {
					this.languageId = value;
				}
				
				/**
				 * Sets the value of the requestUUID property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link String }
				 */
				public void setRequestUUID(String value) {
					this.requestUUID = value;
				}
				
				/**
				 * Sets the value of the serviceRequestId property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link String }
				 */
				public void setServiceRequestId(String value) {
					this.serviceRequestId = value;
				}
				
				/**
				 * Sets the value of the serviceRequestVersion property.
				 */
				public void setServiceRequestVersion(double value) {
					this.serviceRequestVersion = value;
				}
				
			}
			
			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 *
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}int"/>
			 *         &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
			 *         &lt;element name="EntityId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
			 *         &lt;element name="EntityType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
			 *         &lt;element name="ArmCorrelationId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
			 *         &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = {
					"bankId", "timeZone", "entityId", "entityType", "armCorrelationId", "messageDateTime"
			})
			public static class RequestMessageInfo {
				
				@XmlElement(name = "BankId")
				protected int		bankId;
				@XmlElement(name = "TimeZone", required = true)
				protected Object	timeZone;
				@XmlElement(name = "EntityId", required = true)
				protected Object	entityId;
				@XmlElement(name = "EntityType", required = true)
				protected Object	entityType;
				@XmlElement(name = "ArmCorrelationId", required = true)
				protected Object	armCorrelationId;
				@XmlElement(name = "MessageDateTime", required = true)
				protected String	messageDateTime;
				
				/**
				 * Gets the value of the armCorrelationId property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link Object }
				 */
				public Object getArmCorrelationId() {
					return armCorrelationId;
				}
				
				/**
				 * Gets the value of the bankId property.
				 */
				public int getBankId() {
					return bankId;
				}
				
				/**
				 * Gets the value of the entityId property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link Object }
				 */
				public Object getEntityId() {
					return entityId;
				}
				
				/**
				 * Gets the value of the entityType property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link Object }
				 */
				public Object getEntityType() {
					return entityType;
				}
				
				/**
				 * Gets the value of the messageDateTime property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link String }
				 */
				public String getMessageDateTime() {
					return messageDateTime;
				}
				
				/**
				 * Gets the value of the timeZone property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link Object }
				 */
				public Object getTimeZone() {
					return timeZone;
				}
				
				/**
				 * Sets the value of the armCorrelationId property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link Object }
				 */
				public void setArmCorrelationId(Object value) {
					this.armCorrelationId = value;
				}
				
				/**
				 * Sets the value of the bankId property.
				 */
				public void setBankId(int value) {
					this.bankId = value;
				}
				
				/**
				 * Sets the value of the entityId property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link Object }
				 */
				public void setEntityId(Object value) {
					this.entityId = value;
				}
				
				/**
				 * Sets the value of the entityType property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link Object }
				 */
				public void setEntityType(Object value) {
					this.entityType = value;
				}
				
				/**
				 * Sets the value of the messageDateTime property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link String }
				 */
				public void setMessageDateTime(String value) {
					this.messageDateTime = value;
				}
				
				/**
				 * Sets the value of the timeZone property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link Object }
				 */
				public void setTimeZone(Object value) {
					this.timeZone = value;
				}
				
			}
			
			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 *
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="Token">
			 *           &lt;complexType>
			 *             &lt;complexContent>
			 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                 &lt;sequence>
			 *                   &lt;element name="PasswordToken">
			 *                     &lt;complexType>
			 *                       &lt;complexContent>
			 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                           &lt;sequence>
			 *                             &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
			 *                             &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
			 *                           &lt;/sequence>
			 *                         &lt;/restriction>
			 *                       &lt;/complexContent>
			 *                     &lt;/complexType>
			 *                   &lt;/element>
			 *                 &lt;/sequence>
			 *               &lt;/restriction>
			 *             &lt;/complexContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *         &lt;element name="FICertToken" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
			 *         &lt;element name="RealUserLoginSessionId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
			 *         &lt;element name="RealUser" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
			 *         &lt;element name="RealUserPwd" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
			 *         &lt;element name="SSOTransferToken" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = {
					"token", "fiCertToken", "realUserLoginSessionId", "realUser", "realUserPwd", "ssoTransferToken"
			})
			public static class Security {
				
				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 *
				 * <pre>
				 * &lt;complexType>
				 *   &lt;complexContent>
				 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *       &lt;sequence>
				 *         &lt;element name="PasswordToken">
				 *           &lt;complexType>
				 *             &lt;complexContent>
				 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *                 &lt;sequence>
				 *                   &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
				 *                   &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
				 *                 &lt;/sequence>
				 *               &lt;/restriction>
				 *             &lt;/complexContent>
				 *           &lt;/complexType>
				 *         &lt;/element>
				 *       &lt;/sequence>
				 *     &lt;/restriction>
				 *   &lt;/complexContent>
				 * &lt;/complexType>
				 * </pre>
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = {
						"passwordToken"
				})
				public static class Token {
					
					/**
					 * <p>
					 * Java class for anonymous complex type.
					 * <p>
					 * The following schema fragment specifies the expected
					 * content contained within this class.
					 *
					 * <pre>
					 * &lt;complexType>
					 *   &lt;complexContent>
					 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
					 *       &lt;sequence>
					 *         &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
					 *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
					 *       &lt;/sequence>
					 *     &lt;/restriction>
					 *   &lt;/complexContent>
					 * &lt;/complexType>
					 * </pre>
					 */
					@XmlAccessorType(XmlAccessType.FIELD)
					@XmlType(name = "", propOrder = {
							"userId", "password"
					})
					public static class PasswordToken {
						
						@XmlElement(name = "UserId", required = true)
						protected Object	userId;
						@XmlElement(name = "Password", required = true)
						protected Object	password;
						
						/**
						 * Gets the value of the password property.
						 *
						 * @return
						 * 		possible object is
						 *         {@link Object }
						 */
						public Object getPassword() {
							return password;
						}
						
						/**
						 * Gets the value of the userId property.
						 *
						 * @return
						 * 		possible object is
						 *         {@link Object }
						 */
						public Object getUserId() {
							return userId;
						}
						
						/**
						 * Sets the value of the password property.
						 *
						 * @param value
						 *            allowed object is
						 *            {@link Object }
						 */
						public void setPassword(Object value) {
							this.password = value;
						}
						
						/**
						 * Sets the value of the userId property.
						 *
						 * @param value
						 *            allowed object is
						 *            {@link Object }
						 */
						public void setUserId(Object value) {
							this.userId = value;
						}
						
					}
					
					@XmlElement(name = "PasswordToken", required = true)
					protected ReqFixml.Header.RequestHeader.Security.Token.PasswordToken passwordToken;
					
					/**
					 * Gets the value of the passwordToken property.
					 *
					 * @return
					 * 		possible object is
					 *         {@link ReqFixml.Header.RequestHeader.Security.Token.PasswordToken }
					 */
					public ReqFixml.Header.RequestHeader.Security.Token.PasswordToken getPasswordToken() {
						return passwordToken;
					}
					
					/**
					 * Sets the value of the passwordToken property.
					 *
					 * @param value
					 *            allowed object is
					 *            {@link ReqFixml.Header.RequestHeader.Security.Token.PasswordToken }
					 */
					public void setPasswordToken(ReqFixml.Header.RequestHeader.Security.Token.PasswordToken value) {
						this.passwordToken = value;
					}
					
				}
				
				@XmlElement(name = "Token", required = true)
				protected ReqFixml.Header.RequestHeader.Security.Token	token;
				@XmlElement(name = "FICertToken", required = true)
				protected Object										fiCertToken;
				@XmlElement(name = "RealUserLoginSessionId", required = true)
				protected Object										realUserLoginSessionId;
				@XmlElement(name = "RealUser", required = true)
				protected Object										realUser;
				@XmlElement(name = "RealUserPwd", required = true)
				protected Object										realUserPwd;
				
				@XmlElement(name = "SSOTransferToken", required = true)
				protected Object										ssoTransferToken;
				
				/**
				 * Gets the value of the fiCertToken property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link Object }
				 */
				public Object getFICertToken() {
					return fiCertToken;
				}
				
				/**
				 * Gets the value of the realUser property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link Object }
				 */
				public Object getRealUser() {
					return realUser;
				}
				
				/**
				 * Gets the value of the realUserLoginSessionId property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link Object }
				 */
				public Object getRealUserLoginSessionId() {
					return realUserLoginSessionId;
				}
				
				/**
				 * Gets the value of the realUserPwd property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link Object }
				 */
				public Object getRealUserPwd() {
					return realUserPwd;
				}
				
				/**
				 * Gets the value of the ssoTransferToken property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link Object }
				 */
				public Object getSSOTransferToken() {
					return ssoTransferToken;
				}
				
				/**
				 * Gets the value of the token property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link ReqFixml.Header.RequestHeader.Security.Token }
				 */
				public ReqFixml.Header.RequestHeader.Security.Token getToken() {
					return token;
				}
				
				/**
				 * Sets the value of the fiCertToken property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link Object }
				 */
				public void setFICertToken(Object value) {
					this.fiCertToken = value;
				}
				
				/**
				 * Sets the value of the realUser property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link Object }
				 */
				public void setRealUser(Object value) {
					this.realUser = value;
				}
				
				/**
				 * Sets the value of the realUserLoginSessionId property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link Object }
				 */
				public void setRealUserLoginSessionId(Object value) {
					this.realUserLoginSessionId = value;
				}
				
				/**
				 * Sets the value of the realUserPwd property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link Object }
				 */
				public void setRealUserPwd(Object value) {
					this.realUserPwd = value;
				}
				
				/**
				 * Sets the value of the ssoTransferToken property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link Object }
				 */
				public void setSSOTransferToken(Object value) {
					this.ssoTransferToken = value;
				}
				
				/**
				 * Sets the value of the token property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link ReqFixml.Header.RequestHeader.Security.Token }
				 */
				public void setToken(ReqFixml.Header.RequestHeader.Security.Token value) {
					this.token = value;
				}
				
			}
			
			@XmlElement(name = "MessageKey", required = true)
			protected ReqFixml.Header.RequestHeader.MessageKey			messageKey;
			
			@XmlElement(name = "RequestMessageInfo", required = true)
			protected ReqFixml.Header.RequestHeader.RequestMessageInfo	requestMessageInfo;
			
			@XmlElement(name = "Security", required = true)
			protected ReqFixml.Header.RequestHeader.Security			security;
			
			/**
			 * Gets the value of the messageKey property.
			 *
			 * @return
			 * 		possible object is
			 *         {@link ReqFixml.Header.RequestHeader.MessageKey }
			 */
			public ReqFixml.Header.RequestHeader.MessageKey getMessageKey() {
				return messageKey;
			}
			
			/**
			 * Gets the value of the requestMessageInfo property.
			 *
			 * @return
			 * 		possible object is
			 *         {@link ReqFixml.Header.RequestHeader.RequestMessageInfo }
			 */
			public ReqFixml.Header.RequestHeader.RequestMessageInfo getRequestMessageInfo() {
				return requestMessageInfo;
			}
			
			/**
			 * Gets the value of the security property.
			 *
			 * @return
			 * 		possible object is
			 *         {@link ReqFixml.Header.RequestHeader.Security }
			 */
			public ReqFixml.Header.RequestHeader.Security getSecurity() {
				return security;
			}
			
			/**
			 * Sets the value of the messageKey property.
			 *
			 * @param value
			 *            allowed object is
			 *            {@link ReqFixml.Header.RequestHeader.MessageKey }
			 */
			public void setMessageKey(ReqFixml.Header.RequestHeader.MessageKey value) {
				this.messageKey = value;
			}
			
			/**
			 * Sets the value of the requestMessageInfo property.
			 *
			 * @param value
			 *            allowed object is
			 *            {@link ReqFixml.Header.RequestHeader.RequestMessageInfo }
			 */
			public void setRequestMessageInfo(ReqFixml.Header.RequestHeader.RequestMessageInfo value) {
				this.requestMessageInfo = value;
			}
			
			/**
			 * Sets the value of the security property.
			 *
			 * @param value
			 *            allowed object is
			 *            {@link ReqFixml.Header.RequestHeader.Security }
			 */
			public void setSecurity(ReqFixml.Header.RequestHeader.Security value) {
				this.security = value;
			}
			
		}
		
		@XmlElement(name = "RequestHeader", required = true)
		protected ReqFixml.Header.RequestHeader requestHeader;
		
		/**
		 * Gets the value of the requestHeader property.
		 *
		 * @return
		 * 		possible object is
		 *         {@link ReqFixml.Header.RequestHeader }
		 */
		public ReqFixml.Header.RequestHeader getRequestHeader() {
			return requestHeader;
		}
		
		/**
		 * Sets the value of the requestHeader property.
		 *
		 * @param value
		 *            allowed object is
		 *            {@link ReqFixml.Header.RequestHeader }
		 */
		public void setRequestHeader(ReqFixml.Header.RequestHeader value) {
			this.requestHeader = value;
		}
		
	}
	
	@XmlElement(name = "Header", required = true)
	protected ReqFixml.Header	header;
	
	@XmlElement(name = "Body", required = true)
	protected ReqFixml.Body		body;
	
	/**
	 * Gets the value of the body property.
	 *
	 * @return
	 * 		possible object is
	 *         {@link ReqFixml.Body }
	 */
	public ReqFixml.Body getBody() {
		return body;
	}
	
	/**
	 * Gets the value of the header property.
	 *
	 * @return
	 * 		possible object is
	 *         {@link ReqFixml.Header }
	 */
	public ReqFixml.Header getHeader() {
		return header;
	}
	
	/**
	 * Sets the value of the body property.
	 *
	 * @param value
	 *            allowed object is
	 *            {@link ReqFixml.Body }
	 */
	public void setBody(ReqFixml.Body value) {
		this.body = value;
	}
	
	/**
	 * Sets the value of the header property.
	 *
	 * @param value
	 *            allowed object is
	 *            {@link ReqFixml.Header }
	 */
	public void setHeader(ReqFixml.Header value) {
		this.header = value;
	}
	
}
