//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.14 at 11:57:36 AM IST 
//


package com.npst.upiserver.npcischema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for credsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="credsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cred" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Data">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ki" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Meta" type="{http://npci.org/upi/schema/}MetaType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="type" use="required" type="{http://npci.org/upi/schema/}credType" />
 *                 &lt;attribute name="subType" use="required" type="{http://npci.org/upi/schema/}credSubType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "credsType", propOrder = {
    "cred"
})
public class CredsType {

    @XmlElement(name = "Cred", required = true)
    protected List<CredsType.Cred> cred;

    /**
     * Gets the value of the cred property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cred property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCred().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CredsType.Cred }
     * 
     * 
     */
    public List<CredsType.Cred> getCred() {
        if (cred == null) {
            cred = new ArrayList<CredsType.Cred>();
        }
        return this.cred;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Data">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="ki" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Meta" type="{http://npci.org/upi/schema/}MetaType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="type" use="required" type="{http://npci.org/upi/schema/}credType" />
     *       &lt;attribute name="subType" use="required" type="{http://npci.org/upi/schema/}credSubType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "data",
        "meta"
    })
    public static class Cred {

        @XmlElement(name = "Data", required = true)
        protected CredsType.Cred.Data data;
        @XmlElement(name = "Meta")
        protected MetaType meta;
        @XmlAttribute(name = "type", required = true)
        protected CredType type;
        @XmlAttribute(name = "subType", required = true)
        protected CredSubType subType;

        /**
         * Gets the value of the data property.
         * 
         * @return
         *     possible object is
         *     {@link CredsType.Cred.Data }
         *     
         */
        public CredsType.Cred.Data getData() {
            return data;
        }

        /**
         * Sets the value of the data property.
         * 
         * @param value
         *     allowed object is
         *     {@link CredsType.Cred.Data }
         *     
         */
        public void setData(CredsType.Cred.Data value) {
            this.data = value;
        }

        /**
         * Gets the value of the meta property.
         * 
         * @return
         *     possible object is
         *     {@link MetaType }
         *     
         */
        public MetaType getMeta() {
            return meta;
        }

        /**
         * Sets the value of the meta property.
         * 
         * @param value
         *     allowed object is
         *     {@link MetaType }
         *     
         */
        public void setMeta(MetaType value) {
            this.meta = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link CredType }
         *     
         */
        public CredType getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link CredType }
         *     
         */
        public void setType(CredType value) {
            this.type = value;
        }

        /**
         * Gets the value of the subType property.
         * 
         * @return
         *     possible object is
         *     {@link CredSubType }
         *     
         */
        public CredSubType getSubType() {
            return subType;
        }

        /**
         * Sets the value of the subType property.
         * 
         * @param value
         *     allowed object is
         *     {@link CredSubType }
         *     
         */
        public void setSubType(CredSubType value) {
            this.subType = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="ki" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Data {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "code")
            protected String code;
            @XmlAttribute(name = "ki")
            protected String ki;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCode(String value) {
                this.code = value;
            }

            /**
             * Gets the value of the ki property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKi() {
                return ki;
            }

            /**
             * Sets the value of the ki property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKi(String value) {
                this.ki = value;
            }

        }

    }

}
