//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.14 at 11:57:36 AM IST 
//


package com.npst.upiserver.npcischema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for headType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="headType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ver" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ts" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="orgId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="msgId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pageSize" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pageSeqNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pageRecStart" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pageRecEnd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pageTotal" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "headType")
public class HeadType {

    @XmlAttribute(name = "ver", required = true)
    protected String ver;
    @XmlAttribute(name = "ts", required = true)
    protected String ts;
    @XmlAttribute(name = "orgId", required = true)
    protected String orgId;
    @XmlAttribute(name = "msgId", required = true)
    protected String msgId;
    @XmlAttribute(name = "pageSize")
    protected String pageSize;
    @XmlAttribute(name = "pageSeqNum")
    protected String pageSeqNum;
    @XmlAttribute(name = "pageRecStart")
    protected String pageRecStart;
    @XmlAttribute(name = "pageRecEnd")
    protected String pageRecEnd;
    @XmlAttribute(name = "pageTotal")
    protected String pageTotal;
    
    @XmlAttribute(name = "pspOrgId", required = true)
    protected String pspOrgId;

    /**
     * Gets the value of the ver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVer() {
        return ver;
    }

    /**
     * Sets the value of the ver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVer(String value) {
        this.ver = value;
    }

    /**
     * Gets the value of the ts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTs() {
        return ts;
    }

    /**
     * Sets the value of the ts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTs(String value) {
        this.ts = value;
    }

    /**
     * Gets the value of the orgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * Sets the value of the orgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgId(String value) {
        this.orgId = value;
    }

    /**
     * Gets the value of the msgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * Sets the value of the msgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgId(String value) {
        this.msgId = value;
    }

    /**
     * Gets the value of the pageSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageSize() {
        return pageSize;
    }

    /**
     * Sets the value of the pageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageSize(String value) {
        this.pageSize = value;
    }

    /**
     * Gets the value of the pageSeqNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageSeqNum() {
        return pageSeqNum;
    }

    /**
     * Sets the value of the pageSeqNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageSeqNum(String value) {
        this.pageSeqNum = value;
    }

    /**
     * Gets the value of the pageRecStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageRecStart() {
        return pageRecStart;
    }

    /**
     * Sets the value of the pageRecStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageRecStart(String value) {
        this.pageRecStart = value;
    }

    /**
     * Gets the value of the pageRecEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageRecEnd() {
        return pageRecEnd;
    }

    /**
     * Sets the value of the pageRecEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageRecEnd(String value) {
        this.pageRecEnd = value;
    }

    /**
     * Gets the value of the pageTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageTotal() {
        return pageTotal;
    }

    /**
     * Sets the value of the pageTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageTotal(String value) {
        this.pageTotal = value;
    }

	public String getPspOrgId() {
		return pspOrgId;
	}

	public void setPspOrgId(String pspOrgId) {
		this.pspOrgId = pspOrgId;
	}

	

}
