//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2017.07.02 at 10:19:38 PM IST
//

package com.infosys.ci.fiusb.object;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ResponseHeader">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RequestMessageKey">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="ResponseMessageInfo">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="UBUSTransaction">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="HostTransaction">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="HostParentTransaction">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="CustomInfo" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Body">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="executeFinacleScriptResponse">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ExecuteFinacleScriptOutputVO" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="executeFinacleScript_CustomData">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="SuccessOrFailure" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="CustDet">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="CIF_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"header", "body"
})
@XmlRootElement(name = "FIXML")
public class RespFixml {
	
	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="executeFinacleScriptResponse">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="ExecuteFinacleScriptOutputVO" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                   &lt;element name="executeFinacleScript_CustomData">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="SuccessOrFailure" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                             &lt;element name="CustDet">
	 *                               &lt;complexType>
	 *                                 &lt;complexContent>
	 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                     &lt;sequence>
	 *                                       &lt;element name="CIF_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                                     &lt;/sequence>
	 *                                   &lt;/restriction>
	 *                                 &lt;/complexContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"executeFinacleScriptResponse"
	})
	public static class Body {
		
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="ExecuteFinacleScriptOutputVO" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *         &lt;element name="executeFinacleScript_CustomData">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="SuccessOrFailure" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                   &lt;element name="CustDet">
		 *                     &lt;complexType>
		 *                       &lt;complexContent>
		 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                           &lt;sequence>
		 *                             &lt;element name="CIF_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *                           &lt;/sequence>
		 *                         &lt;/restriction>
		 *                       &lt;/complexContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"executeFinacleScriptOutputVO", "executeFinacleScriptCustomData"
		})
		public static class ExecuteFinacleScriptResponse {
			
			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 *
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="SuccessOrFailure" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *         &lt;element name="CustDet">
			 *           &lt;complexType>
			 *             &lt;complexContent>
			 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                 &lt;sequence>
			 *                   &lt;element name="CIF_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
			 *                 &lt;/sequence>
			 *               &lt;/restriction>
			 *             &lt;/complexContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = {
					"successOrFailure", "custDet"
			})
			public static class ExecuteFinacleScriptCustomData {
				
				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 *
				 * <pre>
				 * &lt;complexType>
				 *   &lt;complexContent>
				 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *       &lt;sequence>
				 *         &lt;element name="CIF_ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
				 *       &lt;/sequence>
				 *     &lt;/restriction>
				 *   &lt;/complexContent>
				 * &lt;/complexType>
				 * </pre>
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = {
						"cifid", "custName"
				})
				public static class CustDet {
					
					@XmlElement(name = "CIF_ID")
					protected String cifid;
					
					@XmlElement(name = "CUST_NAME")
					protected String custName;
					
					/**
					 * Gets the value of the cifid property.
					 */
					public String getCIFID() {
						return cifid;
					}
					
					/**
					 * Sets the value of the cifid property.
					 */
					public void setCIFID(String value) {
						this.cifid = value;
					}

					public String getCustName() {
						return custName;
					}

					public void setCustName(String custName) {
						this.custName = custName;
					}
					
				}
				
				@XmlElement(name = "SuccessOrFailure", required = true)
				protected String																					successOrFailure;
				
				@XmlElement(name = "CustDet", required = true)
				protected List<RespFixml.Body.ExecuteFinacleScriptResponse.ExecuteFinacleScriptCustomData.CustDet>	custDet;
				
				/**
				 * Gets the value of the custDet property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link RespFixml.Body.ExecuteFinacleScriptResponse.ExecuteFinacleScriptCustomData.CustDet }
				 */
				public List<RespFixml.Body.ExecuteFinacleScriptResponse.ExecuteFinacleScriptCustomData.CustDet> getCustDet() {
					return custDet;
				}
				
				/**
				 * Gets the value of the successOrFailure property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link String }
				 */
				public String getSuccessOrFailure() {
					return successOrFailure;
				}
				
				/**
				 * Sets the value of the custDet property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link RespFixml.Body.ExecuteFinacleScriptResponse.ExecuteFinacleScriptCustomData.CustDet }
				 */
				public void setCustDet(
						List<RespFixml.Body.ExecuteFinacleScriptResponse.ExecuteFinacleScriptCustomData.CustDet> value) {
					this.custDet = value;
				}
				
				/**
				 * Sets the value of the successOrFailure property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link String }
				 */
				public void setSuccessOrFailure(String value) {
					this.successOrFailure = value;
				}
				
			}
			
			@XmlElement(name = "ExecuteFinacleScriptOutputVO", required = true)
			protected Object																		executeFinacleScriptOutputVO;
			
			@XmlElement(name = "executeFinacleScript_CustomData", required = true)
			protected RespFixml.Body.ExecuteFinacleScriptResponse.ExecuteFinacleScriptCustomData	executeFinacleScriptCustomData;
			
			/**
			 * Gets the value of the executeFinacleScriptCustomData property.
			 *
			 * @return
			 * 		possible object is
			 *         {@link RespFixml.Body.ExecuteFinacleScriptResponse.ExecuteFinacleScriptCustomData }
			 */
			public RespFixml.Body.ExecuteFinacleScriptResponse.ExecuteFinacleScriptCustomData getExecuteFinacleScriptCustomData() {
				return executeFinacleScriptCustomData;
			}
			
			/**
			 * Gets the value of the executeFinacleScriptOutputVO property.
			 *
			 * @return
			 * 		possible object is
			 *         {@link Object }
			 */
			public Object getExecuteFinacleScriptOutputVO() {
				return executeFinacleScriptOutputVO;
			}
			
			/**
			 * Sets the value of the executeFinacleScriptCustomData property.
			 *
			 * @param value
			 *            allowed object is
			 *            {@link RespFixml.Body.ExecuteFinacleScriptResponse.ExecuteFinacleScriptCustomData }
			 */
			public void setExecuteFinacleScriptCustomData(
					RespFixml.Body.ExecuteFinacleScriptResponse.ExecuteFinacleScriptCustomData value) {
				this.executeFinacleScriptCustomData = value;
			}
			
			/**
			 * Sets the value of the executeFinacleScriptOutputVO property.
			 *
			 * @param value
			 *            allowed object is
			 *            {@link Object }
			 */
			public void setExecuteFinacleScriptOutputVO(Object value) {
				this.executeFinacleScriptOutputVO = value;
			}
			
		}
		
		@XmlElement(required = true)
		protected RespFixml.Body.ExecuteFinacleScriptResponse executeFinacleScriptResponse;
		
		/**
		 * Gets the value of the executeFinacleScriptResponse property.
		 *
		 * @return
		 * 		possible object is
		 *         {@link RespFixml.Body.ExecuteFinacleScriptResponse }
		 */
		public RespFixml.Body.ExecuteFinacleScriptResponse getExecuteFinacleScriptResponse() {
			return executeFinacleScriptResponse;
		}
		
		/**
		 * Sets the value of the executeFinacleScriptResponse property.
		 *
		 * @param value
		 *            allowed object is
		 *            {@link RespFixml.Body.ExecuteFinacleScriptResponse }
		 */
		public void setExecuteFinacleScriptResponse(RespFixml.Body.ExecuteFinacleScriptResponse value) {
			this.executeFinacleScriptResponse = value;
		}
		
	}
	
	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="ResponseHeader">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="RequestMessageKey">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                             &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                             &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}double"/>
	 *                             &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="ResponseMessageInfo">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                             &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                             &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="UBUSTransaction">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                             &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="HostTransaction">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                             &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="HostParentTransaction">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                             &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="CustomInfo" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"responseHeader"
	})
	public static class Header {
		
		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="RequestMessageKey">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                   &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                   &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}double"/>
		 *                   &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="ResponseMessageInfo">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *                   &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *                   &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="UBUSTransaction">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="HostTransaction">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="HostParentTransaction">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="CustomInfo" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"requestMessageKey", "responseMessageInfo", "ubusTransaction", "hostTransaction",
				"hostParentTransaction", "customInfo"
		})
		public static class ResponseHeader {
			
			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 *
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
			 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = {
					"id", "status"
			})
			public static class HostParentTransaction {
				
				@XmlElement(name = "Id", required = true)
				protected Object	id;
				@XmlElement(name = "Status", required = true)
				protected Object	status;
				
				/**
				 * Gets the value of the id property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link Object }
				 */
				public Object getId() {
					return id;
				}
				
				/**
				 * Gets the value of the status property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link Object }
				 */
				public Object getStatus() {
					return status;
				}
				
				/**
				 * Sets the value of the id property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link Object }
				 */
				public void setId(Object value) {
					this.id = value;
				}
				
				/**
				 * Sets the value of the status property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link Object }
				 */
				public void setStatus(Object value) {
					this.status = value;
				}
				
			}
			
			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 *
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
			 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = {
					"id", "status"
			})
			public static class HostTransaction {
				
				@XmlElement(name = "Id", required = true)
				protected Object	id;
				@XmlElement(name = "Status", required = true)
				protected String	status;
				
				/**
				 * Gets the value of the id property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link Object }
				 */
				public Object getId() {
					return id;
				}
				
				/**
				 * Gets the value of the status property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link String }
				 */
				public String getStatus() {
					return status;
				}
				
				/**
				 * Sets the value of the id property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link Object }
				 */
				public void setId(Object value) {
					this.id = value;
				}
				
				/**
				 * Sets the value of the status property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link String }
				 */
				public void setStatus(String value) {
					this.status = value;
				}
				
			}
			
			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 *
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="RequestUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *         &lt;element name="ServiceRequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *         &lt;element name="ServiceRequestVersion" type="{http://www.w3.org/2001/XMLSchema}double"/>
			 *         &lt;element name="ChannelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = {
					"requestUUID", "serviceRequestId", "serviceRequestVersion", "channelId"
			})
			public static class RequestMessageKey {
				
				@XmlElement(name = "RequestUUID", required = true)
				protected String	requestUUID;
				@XmlElement(name = "ServiceRequestId", required = true)
				protected String	serviceRequestId;
				@XmlElement(name = "ServiceRequestVersion")
				protected double	serviceRequestVersion;
				@XmlElement(name = "ChannelId", required = true)
				protected String	channelId;
				
				/**
				 * Gets the value of the channelId property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link String }
				 */
				public String getChannelId() {
					return channelId;
				}
				
				/**
				 * Gets the value of the requestUUID property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link String }
				 */
				public String getRequestUUID() {
					return requestUUID;
				}
				
				/**
				 * Gets the value of the serviceRequestId property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link String }
				 */
				public String getServiceRequestId() {
					return serviceRequestId;
				}
				
				/**
				 * Gets the value of the serviceRequestVersion property.
				 */
				public double getServiceRequestVersion() {
					return serviceRequestVersion;
				}
				
				/**
				 * Sets the value of the channelId property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link String }
				 */
				public void setChannelId(String value) {
					this.channelId = value;
				}
				
				/**
				 * Sets the value of the requestUUID property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link String }
				 */
				public void setRequestUUID(String value) {
					this.requestUUID = value;
				}
				
				/**
				 * Sets the value of the serviceRequestId property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link String }
				 */
				public void setServiceRequestId(String value) {
					this.serviceRequestId = value;
				}
				
				/**
				 * Sets the value of the serviceRequestVersion property.
				 */
				public void setServiceRequestVersion(double value) {
					this.serviceRequestVersion = value;
				}
				
			}
			
			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 *
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}int"/>
			 *         &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
			 *         &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = {
					"bankId", "timeZone", "messageDateTime"
			})
			public static class ResponseMessageInfo {
				
				@XmlElement(name = "BankId")
				protected int		bankId;
				@XmlElement(name = "TimeZone", required = true)
				protected Object	timeZone;
				@XmlElement(name = "MessageDateTime", required = true)
				protected String	messageDateTime;
				
				/**
				 * Gets the value of the bankId property.
				 */
				public int getBankId() {
					return bankId;
				}
				
				/**
				 * Gets the value of the messageDateTime property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link String }
				 */
				public String getMessageDateTime() {
					return messageDateTime;
				}
				
				/**
				 * Gets the value of the timeZone property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link Object }
				 */
				public Object getTimeZone() {
					return timeZone;
				}
				
				/**
				 * Sets the value of the bankId property.
				 */
				public void setBankId(int value) {
					this.bankId = value;
				}
				
				/**
				 * Sets the value of the messageDateTime property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link String }
				 */
				public void setMessageDateTime(String value) {
					this.messageDateTime = value;
				}
				
				/**
				 * Sets the value of the timeZone property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link Object }
				 */
				public void setTimeZone(Object value) {
					this.timeZone = value;
				}
				
			}
			
			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 *
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
			 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = {
					"id", "status"
			})
			public static class UBUSTransaction {
				
				@XmlElement(name = "Id", required = true)
				protected Object	id;
				@XmlElement(name = "Status", required = true)
				protected Object	status;
				
				/**
				 * Gets the value of the id property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link Object }
				 */
				public Object getId() {
					return id;
				}
				
				/**
				 * Gets the value of the status property.
				 *
				 * @return
				 * 		possible object is
				 *         {@link Object }
				 */
				public Object getStatus() {
					return status;
				}
				
				/**
				 * Sets the value of the id property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link Object }
				 */
				public void setId(Object value) {
					this.id = value;
				}
				
				/**
				 * Sets the value of the status property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link Object }
				 */
				public void setStatus(Object value) {
					this.status = value;
				}
				
			}
			
			@XmlElement(name = "RequestMessageKey", required = true)
			protected RespFixml.Header.ResponseHeader.RequestMessageKey		requestMessageKey;
			
			@XmlElement(name = "ResponseMessageInfo", required = true)
			protected RespFixml.Header.ResponseHeader.ResponseMessageInfo	responseMessageInfo;
			
			@XmlElement(name = "UBUSTransaction", required = true)
			protected RespFixml.Header.ResponseHeader.UBUSTransaction		ubusTransaction;
			
			@XmlElement(name = "HostTransaction", required = true)
			protected RespFixml.Header.ResponseHeader.HostTransaction		hostTransaction;
			
			@XmlElement(name = "HostParentTransaction", required = true)
			protected RespFixml.Header.ResponseHeader.HostParentTransaction	hostParentTransaction;
			
			@XmlElement(name = "CustomInfo", required = true)
			protected Object												customInfo;
			
			/**
			 * Gets the value of the customInfo property.
			 *
			 * @return
			 * 		possible object is
			 *         {@link Object }
			 */
			public Object getCustomInfo() {
				return customInfo;
			}
			
			/**
			 * Gets the value of the hostParentTransaction property.
			 *
			 * @return
			 * 		possible object is
			 *         {@link RespFixml.Header.ResponseHeader.HostParentTransaction }
			 */
			public RespFixml.Header.ResponseHeader.HostParentTransaction getHostParentTransaction() {
				return hostParentTransaction;
			}
			
			/**
			 * Gets the value of the hostTransaction property.
			 *
			 * @return
			 * 		possible object is
			 *         {@link RespFixml.Header.ResponseHeader.HostTransaction }
			 */
			public RespFixml.Header.ResponseHeader.HostTransaction getHostTransaction() {
				return hostTransaction;
			}
			
			/**
			 * Gets the value of the requestMessageKey property.
			 *
			 * @return
			 * 		possible object is
			 *         {@link RespFixml.Header.ResponseHeader.RequestMessageKey }
			 */
			public RespFixml.Header.ResponseHeader.RequestMessageKey getRequestMessageKey() {
				return requestMessageKey;
			}
			
			/**
			 * Gets the value of the responseMessageInfo property.
			 *
			 * @return
			 * 		possible object is
			 *         {@link RespFixml.Header.ResponseHeader.ResponseMessageInfo }
			 */
			public RespFixml.Header.ResponseHeader.ResponseMessageInfo getResponseMessageInfo() {
				return responseMessageInfo;
			}
			
			/**
			 * Gets the value of the ubusTransaction property.
			 *
			 * @return
			 * 		possible object is
			 *         {@link RespFixml.Header.ResponseHeader.UBUSTransaction }
			 */
			public RespFixml.Header.ResponseHeader.UBUSTransaction getUBUSTransaction() {
				return ubusTransaction;
			}
			
			/**
			 * Sets the value of the customInfo property.
			 *
			 * @param value
			 *            allowed object is
			 *            {@link Object }
			 */
			public void setCustomInfo(Object value) {
				this.customInfo = value;
			}
			
			/**
			 * Sets the value of the hostParentTransaction property.
			 *
			 * @param value
			 *            allowed object is
			 *            {@link RespFixml.Header.ResponseHeader.HostParentTransaction }
			 */
			public void setHostParentTransaction(RespFixml.Header.ResponseHeader.HostParentTransaction value) {
				this.hostParentTransaction = value;
			}
			
			/**
			 * Sets the value of the hostTransaction property.
			 *
			 * @param value
			 *            allowed object is
			 *            {@link RespFixml.Header.ResponseHeader.HostTransaction }
			 */
			public void setHostTransaction(RespFixml.Header.ResponseHeader.HostTransaction value) {
				this.hostTransaction = value;
			}
			
			/**
			 * Sets the value of the requestMessageKey property.
			 *
			 * @param value
			 *            allowed object is
			 *            {@link RespFixml.Header.ResponseHeader.RequestMessageKey }
			 */
			public void setRequestMessageKey(RespFixml.Header.ResponseHeader.RequestMessageKey value) {
				this.requestMessageKey = value;
			}
			
			/**
			 * Sets the value of the responseMessageInfo property.
			 *
			 * @param value
			 *            allowed object is
			 *            {@link RespFixml.Header.ResponseHeader.ResponseMessageInfo }
			 */
			public void setResponseMessageInfo(RespFixml.Header.ResponseHeader.ResponseMessageInfo value) {
				this.responseMessageInfo = value;
			}
			
			/**
			 * Sets the value of the ubusTransaction property.
			 *
			 * @param value
			 *            allowed object is
			 *            {@link RespFixml.Header.ResponseHeader.UBUSTransaction }
			 */
			public void setUBUSTransaction(RespFixml.Header.ResponseHeader.UBUSTransaction value) {
				this.ubusTransaction = value;
			}
			
		}
		
		@XmlElement(name = "ResponseHeader", required = true)
		protected RespFixml.Header.ResponseHeader responseHeader;
		
		/**
		 * Gets the value of the responseHeader property.
		 *
		 * @return
		 * 		possible object is
		 *         {@link RespFixml.Header.ResponseHeader }
		 */
		public RespFixml.Header.ResponseHeader getResponseHeader() {
			return responseHeader;
		}
		
		/**
		 * Sets the value of the responseHeader property.
		 *
		 * @param value
		 *            allowed object is
		 *            {@link RespFixml.Header.ResponseHeader }
		 */
		public void setResponseHeader(RespFixml.Header.ResponseHeader value) {
			this.responseHeader = value;
		}
		
	}
	
	@XmlElement(name = "Header", required = true)
	protected RespFixml.Header	header;
	
	@XmlElement(name = "Body", required = true)
	protected RespFixml.Body	body;
	
	/**
	 * Gets the value of the body property.
	 *
	 * @return
	 * 		possible object is
	 *         {@link RespFixml.Body }
	 */
	public RespFixml.Body getBody() {
		return body;
	}
	
	/**
	 * Gets the value of the header property.
	 *
	 * @return
	 * 		possible object is
	 *         {@link RespFixml.Header }
	 */
	public RespFixml.Header getHeader() {
		return header;
	}
	
	/**
	 * Sets the value of the body property.
	 *
	 * @param value
	 *            allowed object is
	 *            {@link RespFixml.Body }
	 */
	public void setBody(RespFixml.Body value) {
		this.body = value;
	}
	
	/**
	 * Sets the value of the header property.
	 *
	 * @param value
	 *            allowed object is
	 *            {@link RespFixml.Header }
	 */
	public void setHeader(RespFixml.Header value) {
		this.header = value;
	}
	
}
