//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2017.08.09 at 01:53:13 PM IST
//

package com.npst.middleware.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for RequestMessageInfoType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="RequestMessageInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BankId" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="TimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EntityId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EntityType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ArmCorrelationId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MessageDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestMessageInfoType", propOrder = {
		"bankId", "timeZone", "entityId", "entityType", "armCorrelationId", "messageDateTime"
})
public class RequestMessageInfoType {
	
	@XmlElement(name = "BankId")
	protected String	bankId;
	@XmlElement(name = "TimeZone", required = true)
	protected String	timeZone;
	@XmlElement(name = "EntityId", required = true)
	protected String	entityId;
	@XmlElement(name = "EntityType", required = true)
	protected String	entityType;
	@XmlElement(name = "ArmCorrelationId", required = true)
	protected String	armCorrelationId;
	@XmlElement(name = "MessageDateTime", required = true)
	@XmlSchemaType(name = "dateTime")
	protected String	messageDateTime;
	
	public RequestMessageInfoType() {
		super();
	}
	
	public RequestMessageInfoType(String bankId, String timeZone, String entityId, String entityType,
			String armCorrelationId, String messageDateTime) {
		super();
		this.bankId = bankId;
		this.timeZone = timeZone;
		this.entityId = entityId;
		this.entityType = entityType;
		this.armCorrelationId = armCorrelationId;
		this.messageDateTime = messageDateTime;
	}
	
	/**
	 * Gets the value of the armCorrelationId property.
	 *
	 * @return
	 * 		possible object is
	 *         {@link String }
	 */
	public String getArmCorrelationId() {
		return armCorrelationId;
	}
	
	/**
	 * Gets the value of the bankId property.
	 */
	public String getBankId() {
		return bankId;
	}
	
	/**
	 * Gets the value of the entityId property.
	 *
	 * @return
	 * 		possible object is
	 *         {@link String }
	 */
	public String getEntityId() {
		return entityId;
	}
	
	/**
	 * Gets the value of the entityType property.
	 *
	 * @return
	 * 		possible object is
	 *         {@link String }
	 */
	public String getEntityType() {
		return entityType;
	}
	
	/**
	 * Gets the value of the messageDateTime property.
	 *
	 * @return
	 * 		possible object is
	 *         {@link XMLGregorianCalendar }
	 */
	public String getMessageDateTime() {
		return messageDateTime;
	}
	
	/**
	 * Gets the value of the timeZone property.
	 *
	 * @return
	 * 		possible object is
	 *         {@link String }
	 */
	public String getTimeZone() {
		return timeZone;
	}
	
	/**
	 * Sets the value of the armCorrelationId property.
	 *
	 * @param value
	 *            allowed object is
	 *            {@link String }
	 */
	public void setArmCorrelationId(String value) {
		this.armCorrelationId = value;
	}
	
	/**
	 * Sets the value of the bankId property.
	 */
	public void setBankId(String value) {
		this.bankId = value;
	}
	
	/**
	 * Sets the value of the entityId property.
	 *
	 * @param value
	 *            allowed object is
	 *            {@link String }
	 */
	public void setEntityId(String value) {
		this.entityId = value;
	}
	
	/**
	 * Sets the value of the entityType property.
	 *
	 * @param value
	 *            allowed object is
	 *            {@link String }
	 */
	public void setEntityType(String value) {
		this.entityType = value;
	}
	
	/**
	 * Sets the value of the messageDateTime property.
	 *
	 * @param value
	 *            allowed object is
	 *            {@link XMLGregorianCalendar }
	 */
	public void setMessageDateTime(String value) {
		this.messageDateTime = value;
	}
	
	/**
	 * Sets the value of the timeZone property.
	 *
	 * @param value
	 *            allowed object is
	 *            {@link String }
	 */
	public void setTimeZone(String value) {
		this.timeZone = value;
	}
	
}
