package com.npst.upi.hor;
// Generated 6 Apr, 2018 6:24:38 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Securityencryption generated by hbm2java
 */
@Entity
@Table(name = "securityencryption")
public class Securityencryption implements java.io.Serializable {

	private Integer idsecurityencryption;
	private String deviceid;
	private Date updateddate;
	private Date createddate;
	private String ostype;
	private String encryptionkey;
	private Date validtil;
	private int status;
	//private String desc;

	public Securityencryption() {
	}

	public Securityencryption(String deviceid, String encryptionkey, Date validtil, int status) {
		this.deviceid = deviceid;
		this.encryptionkey = encryptionkey;
		this.validtil = validtil;
		this.status = status;
	}

	public Securityencryption(String deviceid, Date updateddate, Date createddate, String ostype, String encryptionkey,
			Date validtil, int status) {
		this.deviceid = deviceid;
		this.updateddate = updateddate;
		this.createddate = createddate;
		this.ostype = ostype;
		this.encryptionkey = encryptionkey;
		this.validtil = validtil;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idsecurityencryption", unique = true, nullable = false)
	public Integer getIdsecurityencryption() {
		return this.idsecurityencryption;
	}

	public void setIdsecurityencryption(Integer idsecurityencryption) {
		this.idsecurityencryption = idsecurityencryption;
	}

	@Column(name = "deviceid", nullable = false, length = 45)
	public String getDeviceid() {
		return this.deviceid;
	}

	public void setDeviceid(String deviceid) {
		this.deviceid = deviceid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", length = 10)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createddate", length = 10)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Column(name = "ostype", length = 45)
	public String getOstype() {
		return this.ostype;
	}

	public void setOstype(String ostype) {
		this.ostype = ostype;
	}

	@Column(name = "encryptionkey", nullable = false, length = 45)
	public String getEncryptionkey() {
		return this.encryptionkey;
	}

	public void setEncryptionkey(String encryptionkey) {
		this.encryptionkey = encryptionkey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "validtil", nullable = false, length = 10)
	public Date getValidtil() {
		return this.validtil;
	}

	public void setValidtil(Date validtil) {
		this.validtil = validtil;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

/*	@Column(name = "desc", nullable = false)
	public String getDesc() {
		return desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}*/


	@Override
	public String toString() {
		return "Securityencryption [idsecurityencryption=" + idsecurityencryption + ", deviceid=" + deviceid
				+ ", updateddate=" + updateddate + ", createddate=" + createddate + ", ostype=" + ostype
				+ ", encryptionkey=" + encryptionkey + ", validtil=" + validtil + ", status=" + status + "]";
	}

	
	
}
