//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.14 at 11:57:36 AM IST 
//


package com.npst.upiserver.npcischema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pspVersionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pspVersionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="no" type="{http://npci.org/upi/schema/}pspVersionNo" />
 *       &lt;attribute name="description" type="{http://npci.org/upi/schema/}pspVersionDesc" />
 *       &lt;attribute name="mandatory" type="{http://npci.org/upi/schema/}pspVersionMandatory" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pspVersionType")
public class PspVersionType {

    @XmlAttribute(name = "no")
    protected String no;
    @XmlAttribute(name = "description")
    protected PspVersionDesc description;
    @XmlAttribute(name = "mandatory")
    protected PspVersionMandatory mandatory;

    /**
     * Gets the value of the no property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNo() {
        return no;
    }

    /**
     * Sets the value of the no property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNo(String value) {
        this.no = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link PspVersionDesc }
     *     
     */
    public PspVersionDesc getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link PspVersionDesc }
     *     
     */
    public void setDescription(PspVersionDesc value) {
        this.description = value;
    }

    /**
     * Gets the value of the mandatory property.
     * 
     * @return
     *     possible object is
     *     {@link PspVersionMandatory }
     *     
     */
    public PspVersionMandatory getMandatory() {
        return mandatory;
    }

    /**
     * Sets the value of the mandatory property.
     * 
     * @param value
     *     allowed object is
     *     {@link PspVersionMandatory }
     *     
     */
    public void setMandatory(PspVersionMandatory value) {
        this.mandatory = value;
    }

}
