//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.14 at 11:57:36 AM IST 
//


package com.npst.upiserver.npcischema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ref complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ref">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type" type="{http://npci.org/upi/schema/}refType" />
 *       &lt;attribute name="seqNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="addr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="settAmount" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="settCurrency" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="approvalNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="respCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="regName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="reversalRespCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="orgAmount" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="acNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IFSC" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="actn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="accType" type="{http://npci.org/upi/schema/}listedAccountType" />
 *       &lt;attribute name="disputeRespCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="adjustmentDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="adjustmentFlag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="adjustmentRaisedBank" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ref")
public class Ref {

    @XmlAttribute(name = "type")
    protected RefType type;
    @XmlAttribute(name = "seqNum")
    protected String seqNum;
    @XmlAttribute(name = "addr")
    protected String addr;
    @XmlAttribute(name = "settAmount")
    protected String settAmount;
    @XmlAttribute(name = "settCurrency")
    protected String settCurrency;
    @XmlAttribute(name = "approvalNum")
    protected String approvalNum;
    @XmlAttribute(name = "respCode")
    protected String respCode;
    @XmlAttribute(name = "regName")
    protected String regName;
    @XmlAttribute(name = "reversalRespCode")
    protected String reversalRespCode;
    @XmlAttribute(name = "orgAmount")
    protected String orgAmount;
    @XmlAttribute(name = "acNum")
    protected String acNum;
    @XmlAttribute(name = "IFSC")
    protected String ifsc;
    @XmlAttribute(name = "code")
    protected String code;
    @XmlAttribute(name = "actn")
    protected String actn;
    @XmlAttribute(name = "accType")
    protected ListedAccountType accType;
    @XmlAttribute(name = "disputeRespCode")
    protected String disputeRespCode;
    @XmlAttribute(name = "adjustmentDate")
    protected String adjustmentDate;
    @XmlAttribute(name = "adjustmentFlag")
    protected String adjustmentFlag;
    @XmlAttribute(name = "adjustmentRaisedBank")
    protected String adjustmentRaisedBank;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link RefType }
     *     
     */
    public RefType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefType }
     *     
     */
    public void setType(RefType value) {
        this.type = value;
    }

    /**
     * Gets the value of the seqNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeqNum() {
        return seqNum;
    }

    /**
     * Sets the value of the seqNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeqNum(String value) {
        this.seqNum = value;
    }

    /**
     * Gets the value of the addr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddr() {
        return addr;
    }

    /**
     * Sets the value of the addr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddr(String value) {
        this.addr = value;
    }

    /**
     * Gets the value of the settAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettAmount() {
        return settAmount;
    }

    /**
     * Sets the value of the settAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettAmount(String value) {
        this.settAmount = value;
    }

    /**
     * Gets the value of the settCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettCurrency() {
        return settCurrency;
    }

    /**
     * Sets the value of the settCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettCurrency(String value) {
        this.settCurrency = value;
    }

    /**
     * Gets the value of the approvalNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovalNum() {
        return approvalNum;
    }

    /**
     * Sets the value of the approvalNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovalNum(String value) {
        this.approvalNum = value;
    }

    /**
     * Gets the value of the respCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespCode() {
        return respCode;
    }

    /**
     * Sets the value of the respCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespCode(String value) {
        this.respCode = value;
    }

    /**
     * Gets the value of the regName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegName() {
        return regName;
    }

    /**
     * Sets the value of the regName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegName(String value) {
        this.regName = value;
    }

    /**
     * Gets the value of the reversalRespCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReversalRespCode() {
        return reversalRespCode;
    }

    /**
     * Sets the value of the reversalRespCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReversalRespCode(String value) {
        this.reversalRespCode = value;
    }

    /**
     * Gets the value of the orgAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgAmount() {
        return orgAmount;
    }

    /**
     * Sets the value of the orgAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgAmount(String value) {
        this.orgAmount = value;
    }

    /**
     * Gets the value of the acNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcNum() {
        return acNum;
    }

    /**
     * Sets the value of the acNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcNum(String value) {
        this.acNum = value;
    }

    /**
     * Gets the value of the ifsc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIFSC() {
        return ifsc;
    }

    /**
     * Sets the value of the ifsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIFSC(String value) {
        this.ifsc = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the actn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActn() {
        return actn;
    }

    /**
     * Sets the value of the actn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActn(String value) {
        this.actn = value;
    }

    /**
     * Gets the value of the accType property.
     * 
     * @return
     *     possible object is
     *     {@link ListedAccountType }
     *     
     */
    public ListedAccountType getAccType() {
        return accType;
    }

    /**
     * Sets the value of the accType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListedAccountType }
     *     
     */
    public void setAccType(ListedAccountType value) {
        this.accType = value;
    }

    /**
     * Gets the value of the disputeRespCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisputeRespCode() {
        return disputeRespCode;
    }

    /**
     * Sets the value of the disputeRespCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisputeRespCode(String value) {
        this.disputeRespCode = value;
    }

    /**
     * Gets the value of the adjustmentDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdjustmentDate() {
        return adjustmentDate;
    }

    /**
     * Sets the value of the adjustmentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdjustmentDate(String value) {
        this.adjustmentDate = value;
    }

    /**
     * Gets the value of the adjustmentFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdjustmentFlag() {
        return adjustmentFlag;
    }

    /**
     * Sets the value of the adjustmentFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdjustmentFlag(String value) {
        this.adjustmentFlag = value;
    }

    /**
     * Gets the value of the adjustmentRaisedBank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdjustmentRaisedBank() {
        return adjustmentRaisedBank;
    }

    /**
     * Sets the value of the adjustmentRaisedBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdjustmentRaisedBank(String value) {
        this.adjustmentRaisedBank = value;
    }

}
