package com.npst.upi.hor;
// Generated 8 Dec, 2017 1:48:54 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Registration generated by hbm2java
 */
@Entity
@Table(name = "registration")
public class Registration implements java.io.Serializable {
	
	private Integer	regid;
	private String	aadhaarno;
	private String	appos;
	private String	appver;
	private Date	blockdt;
	private Date	createddt;
	private String	defvpa;
	private Date	dob;
	private String	emailid;
	private Date	expdt;
	private Integer	faillogincount;
	private String	fname;
	private String	gcmtoken;
	private String	gender;
	private Date	lastchangepassdt;
	private Date	lastlogindt;
	private String	lname;
	private String	loginpin1;
	private String	loginpin2;
	private String	loginpin3;
	private String	mname;
	private String	mobno;
	private String	secans;
	private String	secque;
	private String	servertoken;
	private Date	servertokendt;
	private Integer	status;
	private Date	updateddt;
	private Date	logoutdt;
	private String	deviceid;
	private String	deviceimei;
	
	private String source;
	private String node;
	private String tenantid;
	public Registration() {
	}
	
	public Registration(String aadhaarno, String appos, String appver, Date blockdt, Date createddt, String defvpa,
			Date dob, String emailid, Date expdt, Integer faillogincount, String fname, String gcmtoken, String gender,
			Date lastchangepassdt, Date lastlogindt, String lname, String loginpin1, String loginpin2, String loginpin3,
			String mname, String mobno, String secans, String secque, String servertoken, Date servertokendt,
			Integer status, Date updateddt, Date logoutdt, String deviceid, String deviceimei) {
		this.aadhaarno = aadhaarno;
		this.appos = appos;
		this.appver = appver;
		this.blockdt = blockdt;
		this.createddt = createddt;
		this.defvpa = defvpa;
		this.dob = dob;
		this.emailid = emailid;
		this.expdt = expdt;
		this.faillogincount = faillogincount;
		this.fname = fname;
		this.gcmtoken = gcmtoken;
		this.gender = gender;
		this.lastchangepassdt = lastchangepassdt;
		this.lastlogindt = lastlogindt;
		this.lname = lname;
		this.loginpin1 = loginpin1;
		this.loginpin2 = loginpin2;
		this.loginpin3 = loginpin3;
		this.mname = mname;
		this.mobno = mobno;
		this.secans = secans;
		this.secque = secque;
		this.servertoken = servertoken;
		this.servertokendt = servertokendt;
		this.status = status;
		this.updateddt = updateddt;
		this.logoutdt = logoutdt;
		this.deviceid = deviceid;
		this.deviceimei = deviceimei;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	
	@Column(name = "REGID", unique = true, nullable = false)
	public Integer getRegid() {
		return this.regid;
	}
	
	public void setRegid(Integer regid) {
		this.regid = regid;
	}
	
	@Column(name = "AADHAARNO", length = 12)
	public String getAadhaarno() {
		return this.aadhaarno;
	}
	
	public void setAadhaarno(String aadhaarno) {
		this.aadhaarno = aadhaarno;
	}
	
	@Column(name = "APPOS", length = 20)
	public String getAppos() {
		return this.appos;
	}
	
	public void setAppos(String appos) {
		this.appos = appos;
	}
	
	@Column(name = "APPVER", length = 5)
	public String getAppver() {
		return this.appver;
	}
	
	public void setAppver(String appver) {
		this.appver = appver;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BLOCKDT", length = 19)
	public Date getBlockdt() {
		return this.blockdt;
	}
	
	public void setBlockdt(Date blockdt) {
		this.blockdt = blockdt;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDDT", length = 19)
	public Date getCreateddt() {
		return this.createddt;
	}
	
	public void setCreateddt(Date createddt) {
		this.createddt = createddt;
	}
	
	@Column(name = "DEFVPA", length = 50)
	public String getDefvpa() {
		return this.defvpa;
	}
	
	public void setDefvpa(String defvpa) {
		this.defvpa = defvpa;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DOB", length = 19)
	public Date getDob() {
		return this.dob;
	}
	
	public void setDob(Date dob) {
		this.dob = dob;
	}
	
	@Column(name = "EMAILID", length = 50)
	public String getEmailid() {
		return this.emailid;
	}
	
	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EXPDT", length = 19)
	public Date getExpdt() {
		return this.expdt;
	}
	
	public void setExpdt(Date expdt) {
		this.expdt = expdt;
	}
	
	@Column(name = "FAILLOGINCOUNT")
	public Integer getFaillogincount() {
		return this.faillogincount;
	}
	
	public void setFaillogincount(Integer faillogincount) {
		this.faillogincount = faillogincount;
	}
	
	@Column(name = "FNAME", length = 50)
	public String getFname() {
		return this.fname;
	}
	
	public void setFname(String fname) {
		this.fname = fname;
	}
	
	@Column(name = "GCMTOKEN", length = 1000)
	public String getGcmtoken() {
		return this.gcmtoken;
	}
	
	public void setGcmtoken(String gcmtoken) {
		this.gcmtoken = gcmtoken;
	}
	
	@Column(name = "GENDER", length = 11)
	public String getGender() {
		return this.gender;
	}
	
	public void setGender(String gender) {
		this.gender = gender;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LASTCHANGEPASSDT", length = 19)
	public Date getLastchangepassdt() {
		return this.lastchangepassdt;
	}
	
	public void setLastchangepassdt(Date lastchangepassdt) {
		this.lastchangepassdt = lastchangepassdt;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LASTLOGINDT", length = 19)
	public Date getLastlogindt() {
		return this.lastlogindt;
	}
	
	public void setLastlogindt(Date lastlogindt) {
		this.lastlogindt = lastlogindt;
	}
	
	@Column(name = "LNAME", length = 50)
	public String getLname() {
		return this.lname;
	}
	
	public void setLname(String lname) {
		this.lname = lname;
	}
	
	@Column(name = "LOGINPIN1", length = 100)
	public String getLoginpin1() {
		return this.loginpin1;
	}
	
	public void setLoginpin1(String loginpin1) {
		this.loginpin1 = loginpin1;
	}
	
	@Column(name = "LOGINPIN2", length = 100)
	public String getLoginpin2() {
		return this.loginpin2;
	}
	
	public void setLoginpin2(String loginpin2) {
		this.loginpin2 = loginpin2;
	}
	
	@Column(name = "LOGINPIN3", length = 100)
	public String getLoginpin3() {
		return this.loginpin3;
	}
	
	public void setLoginpin3(String loginpin3) {
		this.loginpin3 = loginpin3;
	}
	
	@Column(name = "MNAME", length = 50)
	public String getMname() {
		return this.mname;
	}
	
	public void setMname(String mname) {
		this.mname = mname;
	}
	
	@Column(name = "MOBNO", length = 12)
	public String getMobno() {
		return this.mobno;
	}
	
	public void setMobno(String mobno) {
		this.mobno = mobno;
	}
	
	@Column(name = "SECANS", length = 50)
	public String getSecans() {
		return this.secans;
	}
	
	public void setSecans(String secans) {
		this.secans = secans;
	}
	
	@Column(name = "SECQUE", length = 80)
	public String getSecque() {
		return this.secque;
	}
	
	public void setSecque(String secque) {
		this.secque = secque;
	}
	
	@Column(name = "SERVERTOKEN", length = 35)
	public String getServertoken() {
		return this.servertoken;
	}
	
	public void setServertoken(String servertoken) {
		this.servertoken = servertoken;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SERVERTOKENDT", length = 19)
	public Date getServertokendt() {
		return this.servertokendt;
	}
	
	public void setServertokendt(Date servertokendt) {
		this.servertokendt = servertokendt;
	}
	
	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}
	
	public void setStatus(Integer status) {
		this.status = status;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEDDT", length = 19)
	public Date getUpdateddt() {
		return this.updateddt;
	}
	
	public void setUpdateddt(Date updateddt) {
		this.updateddt = updateddt;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LOGOUTDT", length = 19)
	public Date getLogoutdt() {
		return this.logoutdt;
	}
	
	public void setLogoutdt(Date logoutdt) {
		this.logoutdt = logoutdt;
	}
	
	@Column(name = "DEVICEID", length = 50)
	public String getDeviceid() {
		return this.deviceid;
	}
	
	public void setDeviceid(String deviceid) {
		this.deviceid = deviceid;
	}
	
	@Column(name = "DEVICEIMEI", length = 50)
	public String getDeviceimei() {
		return this.deviceimei;
	}
	
	public void setDeviceimei(String deviceimei) {
		this.deviceimei = deviceimei;
	}

	@Column(name="SOURCE" , length = 20)
	public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name="NODE" , length = 10)
	public String getNode() {
		return node;
	}

	public void setNode(String node) {
		this.node = node;
	}
	@Column(name="SOCIETYID" , length = 20)
	public String getTenantid() {
		return tenantid;
	}

	public void setTenantid(String tenantid) {
		this.tenantid = tenantid;
	}

	@Override
	public String toString() {
		return "Registration [regid=" + regid + ", aadhaarno=" + aadhaarno + ", appos=" + appos + ", appver=" + appver
				+ ", blockdt=" + blockdt + ", createddt=" + createddt + ", defvpa=" + defvpa + ", dob=" + dob
				+ ", emailid=" + emailid + ", expdt=" + expdt + ", faillogincount=" + faillogincount + ", fname="
				+ fname + ", gcmtoken=" + gcmtoken + ", gender=" + gender + ", lastchangepassdt=" + lastchangepassdt
				+ ", lastlogindt=" + lastlogindt + ", lname=" + lname + ", loginpin1=" + loginpin1 + ", loginpin2="
				+ loginpin2 + ", loginpin3=" + loginpin3 + ", mname=" + mname + ", mobno=" + mobno + ", secans="
				+ secans + ", secque=" + secque + ", servertoken=" + servertoken + ", servertokendt=" + servertokendt
				+ ", status=" + status + ", updateddt=" + updateddt + ", logoutdt=" + logoutdt + ", deviceid="
				+ deviceid + ", deviceimei=" + deviceimei + ", source=" + source + ", node=" + node + ", tenantid="
				+ tenantid + "]";
	}
}
