//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2017.02.01 at 09:58:09 PM IST
//

package org.npci.upi.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="errorMessages" type="{http://npci.org/upi/schema/}errorMessage" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="api" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="reqMsgId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="err" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ts" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "errorMessages" })
@XmlRootElement(name = "Ack")
public class Ack {

	protected List<ErrorMessage> errorMessages;
	@XmlAttribute(name = "api")
	protected String api;
	@XmlAttribute(name = "reqMsgId")
	protected String reqMsgId;
	@XmlAttribute(name = "err")
	protected String err;
	@XmlAttribute(name = "ts")
	protected String ts;

	/**
	 * Gets the value of the api property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getApi() {
		return api;
	}

	/**
	 * Gets the value of the err property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getErr() {
		return err;
	}

	/**
	 * Gets the value of the errorMessages property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the errorMessages property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getErrorMessages().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link ErrorMessage
	 * }
	 */
	public List<ErrorMessage> getErrorMessages() {
		if (errorMessages == null) {
			errorMessages = new ArrayList<ErrorMessage>();
		}
		return this.errorMessages;
	}

	/**
	 * Gets the value of the reqMsgId property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getReqMsgId() {
		return reqMsgId;
	}

	/**
	 * Gets the value of the ts property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getTs() {
		return ts;
	}

	/**
	 * Sets the value of the api property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setApi(String value) {
		this.api = value;
	}

	/**
	 * Sets the value of the err property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setErr(String value) {
		this.err = value;
	}

	/**
	 * Sets the value of the reqMsgId property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setReqMsgId(String value) {
		this.reqMsgId = value;
	}

	/**
	 * Sets the value of the ts property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setTs(String value) {
		this.ts = value;
	}

}
