//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2017.02.01 at 09:58:09 PM IST
//

package org.npci.upi.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ref complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ref">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type" type="{http://npci.org/upi/schema/}refType" />
 *       &lt;attribute name="seqNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="addr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="settAmount" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="settCurrency" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="approvalNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="respCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="regName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="reversalRespCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="orgAmount" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ref")
public class Ref {

	@XmlAttribute(name = "type")
	protected RefType type;
	@XmlAttribute(name = "seqNum")
	protected String seqNum;
	@XmlAttribute(name = "addr")
	protected String addr;
	@XmlAttribute(name = "settAmount")
	protected String settAmount;
	@XmlAttribute(name = "settCurrency")
	protected String settCurrency;
	@XmlAttribute(name = "approvalNum")
	protected String approvalNum;
	@XmlAttribute(name = "respCode")
	protected String respCode;
	@XmlAttribute(name = "regName")
	protected String regName;
	@XmlAttribute(name = "reversalRespCode")
	protected String reversalRespCode;
	@XmlAttribute(name = "orgAmount")
	protected String orgAmount;

	/**
	 * Gets the value of the addr property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getAddr() {
		return addr;
	}

	/**
	 * Gets the value of the approvalNum property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getApprovalNum() {
		return approvalNum;
	}

	/**
	 * Gets the value of the orgAmount property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getOrgAmount() {
		return orgAmount;
	}

	/**
	 * Gets the value of the regName property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getRegName() {
		return regName;
	}

	/**
	 * Gets the value of the respCode property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getRespCode() {
		return respCode;
	}

	/**
	 * Gets the value of the reversalRespCode property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getReversalRespCode() {
		return reversalRespCode;
	}

	/**
	 * Gets the value of the seqNum property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getSeqNum() {
		return seqNum;
	}

	/**
	 * Gets the value of the settAmount property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getSettAmount() {
		return settAmount;
	}

	/**
	 * Gets the value of the settCurrency property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getSettCurrency() {
		return settCurrency;
	}

	/**
	 * Gets the value of the type property.
	 *
	 * @return possible object is {@link RefType }
	 */
	public RefType getType() {
		return type;
	}

	/**
	 * Sets the value of the addr property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setAddr(String value) {
		this.addr = value;
	}

	/**
	 * Sets the value of the approvalNum property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setApprovalNum(String value) {
		this.approvalNum = value;
	}

	/**
	 * Sets the value of the orgAmount property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setOrgAmount(String value) {
		this.orgAmount = value;
	}

	/**
	 * Sets the value of the regName property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setRegName(String value) {
		this.regName = value;
	}

	/**
	 * Sets the value of the respCode property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setRespCode(String value) {
		this.respCode = value;
	}

	/**
	 * Sets the value of the reversalRespCode property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setReversalRespCode(String value) {
		this.reversalRespCode = value;
	}

	/**
	 * Sets the value of the seqNum property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setSeqNum(String value) {
		this.seqNum = value;
	}

	/**
	 * Sets the value of the settAmount property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setSettAmount(String value) {
		this.settAmount = value;
	}

	/**
	 * Sets the value of the settCurrency property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setSettCurrency(String value) {
		this.settCurrency = value;
	}

	/**
	 * Sets the value of the type property.
	 *
	 * @param value
	 *            allowed object is {@link RefType }
	 */
	public void setType(RefType value) {
		this.type = value;
	}

}
