//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2017.02.01 at 09:58:09 PM IST
//

package org.npci.upi.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for amountType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="amountType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Split" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="name" use="required" type="{http://npci.org/upi/schema/}amountSplitConstant" />
 *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="curr" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "amountType", propOrder = { "split" })
public class AmountType {

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;attribute name="name" use="required" type="{http://npci.org/upi/schema/}amountSplitConstant" />
	 *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class Split {

		@XmlAttribute(name = "name", required = true)
		protected AmountSplitConstant name;
		@XmlAttribute(name = "value", required = true)
		protected String value;

		/**
		 * Gets the value of the name property.
		 *
		 * @return possible object is {@link AmountSplitConstant }
		 */
		public AmountSplitConstant getName() {
			return name;
		}

		/**
		 * Gets the value of the value property.
		 *
		 * @return possible object is {@link String }
		 */
		public String getValue() {
			return value;
		}

		/**
		 * Sets the value of the name property.
		 *
		 * @param value
		 *            allowed object is {@link AmountSplitConstant }
		 */
		public void setName(AmountSplitConstant value) {
			this.name = value;
		}

		/**
		 * Sets the value of the value property.
		 *
		 * @param value
		 *            allowed object is {@link String }
		 */
		public void setValue(String value) {
			this.value = value;
		}

	}

	@XmlElement(name = "Split")
	protected AmountType.Split split;
	@XmlAttribute(name = "value", required = true)
	protected String value;

	@XmlAttribute(name = "curr", required = true)
	protected String curr;

	/**
	 * Gets the value of the curr property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getCurr() {
		return curr;
	}

	/**
	 * Gets the value of the split property.
	 *
	 * @return possible object is {@link AmountType.Split }
	 */
	public AmountType.Split getSplit() {
		return split;
	}

	/**
	 * Gets the value of the value property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getValue() {
		return value;
	}

	/**
	 * Sets the value of the curr property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setCurr(String value) {
		this.curr = value;
	}

	/**
	 * Sets the value of the split property.
	 *
	 * @param value
	 *            allowed object is {@link AmountType.Split }
	 */
	public void setSplit(AmountType.Split value) {
		this.split = value;
	}

	/**
	 * Sets the value of the value property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setValue(String value) {
		this.value = value;
	}

}
