package com.npst.upi.hor;
// Generated 15 Mar, 2018 2:07:42 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Appversion generated by hbm2java
 */
@Entity
@Table(name = "appversion")
public class Appversion implements java.io.Serializable {

	private Integer id;
	private String appversion;
	private String appos;
	private String action;
	private String createdby;
	private String modifiedby;
	private Date createddate;
	private Date modifieddate;
	private String appurl;
	private String status;

	public Appversion() {
	}

	public Appversion(String appversion, String appos, String action, String createdby, Date createddate,
			String appurl) {
		this.appversion = appversion;
		this.appos = appos;
		this.action = action;
		this.createdby = createdby;
		this.createddate = createddate;
		this.appurl = appurl;
	}

	public Appversion(String appversion, String appos, String action, String createdby, String modifiedby,
			Date createddate, Date modifieddate, String appurl) {
		this.appversion = appversion;
		this.appos = appos;
		this.action = action;
		this.createdby = createdby;
		this.modifiedby = modifiedby;
		this.createddate = createddate;
		this.modifieddate = modifieddate;
		this.appurl = appurl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "app_ver", nullable = false, length = 45)
	public String getAppversion() {
		return this.appversion;
	}

	public void setAppversion(String appversion) {
		this.appversion = appversion;
	}

	@Column(name = "os_name", nullable = false, length = 45)
	public String getAppos() {
		return this.appos;
	}

	public void setAppos(String appos) {
		this.appos = appos;
	}

	@Column(name = "upgrade_type", nullable = false, length = 45)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "createdby", nullable = false, length = 45)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "modifiedby", length = 45)
	public String getModifiedby() {
		return this.modifiedby;
	}

	public void setModifiedby(String modifiedby) {
		this.modifiedby = modifiedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createddate", nullable = false, length = 10)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifieddate", length = 10)
	public Date getModifieddate() {
		return this.modifieddate;
	}

	public void setModifieddate(Date modifieddate) {
		this.modifieddate = modifieddate;
	}

	@Column(name = "upgrade_url", nullable = false, length = 500)
	public String getAppurl() {
		return this.appurl;
	}

	public void setAppurl(String appurl) {
		this.appurl = appurl;
	}

	@Column(name = "STATUS", nullable = false, length = 500)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	
}
