package com.npst.upi.hor;
// Generated 5 Mar, 2017 5:02:39 PM by Hibernate Tools 5.2.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mobreqrespjson generated by hbm2java
 */
@Entity
@Table(name = "mobupireqrespjson")
public class Mobupireqrespjson implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idPk;
	private String req;
	private String resp;
	private Date reqDate;
	private Date respDate;
	private String type;
	private Integer flag;
	private String              tpId;
	private String              source;
	private String              node;

	public Mobupireqrespjson() {
	}

	public Mobupireqrespjson(String req, String resp, Date reqDate, Date respDate, String type, Integer flag) {
		this.req = req;
		this.resp = resp;
		this.reqDate = reqDate;
		this.respDate = respDate;
		this.type = type;
		this.flag = flag;
	}

	@Column(name = "Flag")
	public Integer getFlag() {
		return this.flag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IdPk", unique = true, nullable = false)
	public Integer getIdPk() {
		return idPk;
	}

	@Column(name = "Req", length = 16777215)
	public String getReq() {
		return this.req;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ReqDate", length = 19)
	public Date getReqDate() {
		return this.reqDate;
	}

	@Column(name = "Resp", length = 16777215)
	public String getResp() {
		return this.resp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RespDate", length = 19)
	public Date getRespDate() {
		return this.respDate;
	}

	@Column(name = "Type", length = 20)
	public String getType() {
		return this.type;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	public void setIdPk(Integer idPk) {
		this.idPk = idPk;
	}

	public void setReq(String req) {
		this.req = req;
	}

	public void setReqDate(Date reqDate) {
		this.reqDate = reqDate;
	}

	public void setResp(String resp) {
		this.resp = resp;
	}

	public void setRespDate(Date respDate) {
		this.respDate = respDate;
	}

	public void setType(String type) {
		this.type = type;
	}
	@Column(name = "TPID", length = 50)
	public String getTpId() {
		return tpId;
	}

	public void setTpId(String tpId) {
		this.tpId = tpId;
	}
	@Column(name = "SOURCE", length = 99)
	public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}
	@Column(name = "NODE", length = 99)
	public String getNode() {
		return node;
	}

	public void setNode(String node) {
		this.node = node;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Mobupireqrespjson [");
		if (idPk != null) {
			builder.append("idPk=");
			builder.append(idPk);
			builder.append(", ");
		}
		if (req != null) {
			builder.append("req=");
			builder.append(req);
			builder.append(", ");
		}
		if (resp != null) {
			builder.append("resp=");
			builder.append(resp);
			builder.append(", ");
		}
		if (reqDate != null) {
			builder.append("reqDate=");
			builder.append(reqDate);
			builder.append(", ");
		}
		if (respDate != null) {
			builder.append("respDate=");
			builder.append(respDate);
			builder.append(", ");
		}
		if (type != null) {
			builder.append("type=");
			builder.append(type);
			builder.append(", ");
		}
		if (flag != null) {
			builder.append("flag=");
			builder.append(flag);
		}
		if (tpId != null) {
			builder.append("tpId=");
			builder.append(tpId);
		}
		if (source != null) {
			builder.append("source=");
			builder.append(source);
		}
		if (node != null) {
			builder.append("node=");
			builder.append(node);
		}
		builder.append("]");
		return builder.toString();
	}

}
