//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2017.08.09 at 01:53:13 PM IST
//

package com.npst.middleware.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for BodyType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="BodyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="executeFinacleScriptRequest" type="{http://www.finacle.com/fixml}executeFinacleScriptRequestType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BodyType", propOrder = {
		"executeFinacleScriptRequest",
		"acctLienAddRequest"
})
public class BodyType {
	
	@XmlElement(required = true)
	protected ExecuteFinacleScriptRequestType executeFinacleScriptRequest;
	
	 @XmlElement(name = "AcctLienAddRequest", required = true)
     protected AcctLienAddRequest acctLienAddRequest;
	
	public BodyType() {
		super();
	}
	
	public BodyType(ExecuteFinacleScriptRequestType executeFinacleScriptRequest) {
		super();
		this.executeFinacleScriptRequest = executeFinacleScriptRequest;
	}
	
	/**
	 * Gets the value of the executeFinacleScriptRequest property.
	 *
	 * @return
	 * 		possible object is
	 *         {@link ExecuteFinacleScriptRequestType }
	 */
	public ExecuteFinacleScriptRequestType getExecuteFinacleScriptRequest() {
		return executeFinacleScriptRequest;
	}
	
	/**
	 * Sets the value of the executeFinacleScriptRequest property.
	 *
	 * @param value
	 *            allowed object is
	 *            {@link ExecuteFinacleScriptRequestType }
	 */
	public void setExecuteFinacleScriptRequest(ExecuteFinacleScriptRequestType value) {
		this.executeFinacleScriptRequest = value;
	}
	
	
	
	 /**
     * Gets the value of the acctLienAddRequest property.
     * 
     * @return
     *     possible object is
     *     {@link FIXML.Body.AcctLienAddRequest }
     *     
     */
    public AcctLienAddRequest getAcctLienAddRequest() {
        return acctLienAddRequest;
    }

    /**
     * Sets the value of the acctLienAddRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link FIXML.Body.AcctLienAddRequest }
     *     
     */
    public void setAcctLienAddRequest(AcctLienAddRequest value) {
        this.acctLienAddRequest = value;
    }

	public BodyType(AcctLienAddRequest acctLienAddRequest) {
		super();
		this.acctLienAddRequest = acctLienAddRequest;
	}


}
