//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2017.08.09 at 01:53:13 PM IST
//

package com.npst.middleware.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for executeFinacleScript_CustomDataType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="executeFinacleScript_CustomDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MOBILENO" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "executeFinacleScript_CustomDataType", propOrder = {
		"mobileno", "aadhaarNo"
})
public class ExecuteFinacleScriptCustomDataType {
	
	@XmlElement(name = "MOBILENO")
	protected String mobileno;
	@XmlElement(name = "aadhaarNo")
	protected String aadhaarNo;
	
	public ExecuteFinacleScriptCustomDataType() {
		super();
	}
	
	public ExecuteFinacleScriptCustomDataType(String mobileno, String aadhaarNo) {
		super();
		this.mobileno = mobileno;
		this.aadhaarNo=aadhaarNo;
	}
	
	/**
	 * Gets the value of the mobileno property.
	 */
	public String getMOBILENO() {
		return mobileno;
	}
	
	/**
	 * Sets the value of the mobileno property.
	 */
	public void setMOBILENO(String value) {
		this.mobileno = value;
	}

	public String getAadhaarNo() {
		return aadhaarNo;
	}

	public void setAadhaarNo(String aadhaarNo) {
		this.aadhaarNo = aadhaarNo;
	}
	
}
